var sales = [
{ "ProductCategory": "Clothing", "UnitPrice": 12.814, "SellerName": "Stanley Brooker", "Country": "Uruguay", "City": "Montevideo", "Date": "01/01/2007", "UnitsSold": 282 },
{ "ProductCategory": "Clothing", "UnitPrice": 49.579, "SellerName": "Elisa Longbottom", "Country": "UK", "City": "Cambrige", "Date": "01/05/2007", "UnitsSold": 296 },
{ "ProductCategory": "Bikes", "UnitPrice": 3.565, "SellerName": "Lydia Burson", "Country": "Bulgaria", "City": "Sofia", "Date": "01/06/2007", "UnitsSold": 68 },
{ "ProductCategory": "Accessories", "UnitPrice": 85.581, "SellerName": "David Haley", "Country": "Germany", "City": "Heidelberg", "Date": "01/07/2007", "UnitsSold": 293 },
{ "ProductCategory": "Components", "UnitPrice": 18.137, "SellerName": "John Smith", "Country": "UK", "City": "Oxford", "Date": "01/08/2007", "UnitsSold": 240 },
{ "ProductCategory": "Clothing", "UnitPrice": 68.330, "SellerName": "Larry Lieb", "Country": "UK", "City": "London", "Date": "01/12/2007", "UnitsSold": 456 },
{ "ProductCategory": "Components", "UnitPrice": 16.056, "SellerName": "Walter Pang", "Country": "UK", "City": "Birmingham", "Date": "02/09/2007", "UnitsSold": 492 },
{ "ProductCategory": "Components", "UnitPrice": 35.235, "SellerName": "Benjamin Dupree", "Country": "Uruguay", "City": "Montevideo", "Date": "02/16/2007", "UnitsSold": 78 },
{ "ProductCategory": "Accessories", "UnitPrice": 73.215, "SellerName": "Nicholas Carmona", "Country": "Germany", "City": "Heidelberg", "Date": "02/17/2007", "UnitsSold": 150 },
{ "ProductCategory": "Clothing", "UnitPrice": 73.614, "SellerName": "Nicholas Carmona", "Country": "Japan", "City": "Tokyo", "Date": "02/19/2007", "UnitsSold": 262 },
{ "ProductCategory": "Bikes", "UnitPrice": 47.080, "SellerName": "Monica Freitag", "Country": "UK", "City": "Liverpool", "Date": "02/21/2007", "UnitsSold": 125 },
{ "ProductCategory": "Clothing", "UnitPrice": 51.298, "SellerName": "Kathe Pettel", "Country": "UK", "City": "Cambrige", "Date": "03/04/2007", "UnitsSold": 42 },
{ "ProductCategory": "Bikes", "UnitPrice": 27.466, "SellerName": "David Haley", "Country": "Japan", "City": "Yokohama", "Date": "03/04/2007", "UnitsSold": 282 },
{ "ProductCategory": "Accessories", "UnitPrice": 22.374, "SellerName": "Antonio Charbonneau", "Country": "Uruguay", "City": "Montevideo", "Date": "03/17/2007", "UnitsSold": 305 },
{ "ProductCategory": "Clothing", "UnitPrice": 85.292, "SellerName": "Glenn Landeros", "Country": "Germany", "City": "Heidelberg", "Date": "03/23/2007", "UnitsSold": 265 },
{ "ProductCategory": "Accessories", "UnitPrice": 80.675, "SellerName": "Elisa Longbottom", "Country": "UK", "City": "Oxford", "Date": "03/25/2007", "UnitsSold": 350 },
{ "ProductCategory": "Components", "UnitPrice": 64.613, "SellerName": "Glenn Landeros", "Country": "US", "City": "Lincoln", "Date": "03/27/2007", "UnitsSold": 82 },
{ "ProductCategory": "Accessories", "UnitPrice": 50.041, "SellerName": "Harry Tyler", "Country": "Uruguay", "City": "Montevideo", "Date": "04/02/2007", "UnitsSold": 67 },
{ "ProductCategory": "Accessories", "UnitPrice": 16.311, "SellerName": "Brandon Mckim", "Country": "Bulgaria", "City": "Plovdiv", "Date": "04/04/2007", "UnitsSold": 370 },
{ "ProductCategory": "Accessories", "UnitPrice": 49.852, "SellerName": "Monica Freitag", "Country": "US", "City": "Cranbury", "Date": "04/12/2007", "UnitsSold": 228 },
{ "ProductCategory": "Components", "UnitPrice": 44.761, "SellerName": "Bryan Culver", "Country": "UK", "City": "London", "Date": "04/15/2007", "UnitsSold": 272 },
{ "ProductCategory": "Components", "UnitPrice": 44.395, "SellerName": "Russell Shorter", "Country": "Uruguay", "City": "Montevideo", "Date": "04/18/2007", "UnitsSold": 227 },
{ "ProductCategory": "Components", "UnitPrice": 39.287, "SellerName": "Stanley Brooker", "Country": "Bulgaria", "City": "Sofia", "Date": "04/18/2007", "UnitsSold": 248 },
{ "ProductCategory": "Accessories", "UnitPrice": 36.581, "SellerName": "Benjamin Meekins", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "04/21/2007", "UnitsSold": 414 },
{ "ProductCategory": "Clothing", "UnitPrice": 75.828, "SellerName": "Walter Pang", "Country": "Japan", "City": "Tokyo", "Date": "04/25/2007", "UnitsSold": 43 },
{ "ProductCategory": "Components", "UnitPrice": 57.757, "SellerName": "Antonio Charbonneau", "Country": "Japan", "City": "Yokohama", "Date": "04/26/2007", "UnitsSold": 71 },
{ "ProductCategory": "Components", "UnitPrice": 40.231, "SellerName": "Stanley Brooker", "Country": "UK", "City": "Cambrige", "Date": "05/14/2007", "UnitsSold": 321 },
{ "ProductCategory": "Accessories", "UnitPrice": 49.525, "SellerName": "Elisa Longbottom", "Country": "Uruguay", "City": "Montevideo", "Date": "05/17/2007", "UnitsSold": 329 },
{ "ProductCategory": "Clothing", "UnitPrice": 56.460, "SellerName": "Benjamin Dupree", "Country": "Japan", "City": "Osaka", "Date": "05/17/2007", "UnitsSold": 88 },
{ "ProductCategory": "Clothing", "UnitPrice": 67.129, "SellerName": "Glenn Landeros", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "05/26/2007", "UnitsSold": 366 },
{ "ProductCategory": "Components", "UnitPrice": 14.628, "SellerName": "Walter Pang", "Country": "Germany", "City": "Hamburg", "Date": "06/02/2007", "UnitsSold": 450 },
{ "ProductCategory": "Components", "UnitPrice": 89.260, "SellerName": "Howard Sprouse", "Country": "UK", "City": "Cambrige", "Date": "06/06/2007", "UnitsSold": 475 },
{ "ProductCategory": "Components", "UnitPrice": 33.752, "SellerName": "Nicholas Carmona", "Country": "US", "City": "Minneapolis", "Date": "06/11/2007", "UnitsSold": 195 },
{ "ProductCategory": "Bikes", "UnitPrice": 54.101, "SellerName": "Harold Garvin", "Country": "Germany", "City": "Hamburg", "Date": "06/17/2007", "UnitsSold": 458 },
{ "ProductCategory": "Clothing", "UnitPrice": 18.437, "SellerName": "Benjamin Dupree", "Country": "UK", "City": "Oxford", "Date": "07/04/2007", "UnitsSold": 7 },
{ "ProductCategory": "Bikes", "UnitPrice": 96.142, "SellerName": "Elisa Longbottom", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "07/08/2007", "UnitsSold": 158 },
{ "ProductCategory": "Clothing", "UnitPrice": 22.990, "SellerName": "Benjamin Meekins", "Country": "US", "City": "Mellvile", "Date": "07/09/2007", "UnitsSold": 34 },
{ "ProductCategory": "Components", "UnitPrice": 52.664, "SellerName": "Larry Lieb", "Country": "Uruguay", "City": "Montevideo", "Date": "07/10/2007", "UnitsSold": 412 },
{ "ProductCategory": "Accessories", "UnitPrice": 62.127, "SellerName": "John Smith", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "07/15/2007", "UnitsSold": 10 },
{ "ProductCategory": "Accessories", "UnitPrice": 10.722, "SellerName": "Antonio Charbonneau", "Country": "US", "City": "Minneapolis", "Date": "07/16/2007", "UnitsSold": 466 },
{ "ProductCategory": "Components", "UnitPrice": 4.693, "SellerName": "Stanley Brooker", "Country": "Japan", "City": "Tokyo", "Date": "07/20/2007", "UnitsSold": 248 },
{ "ProductCategory": "Clothing", "UnitPrice": 43.724, "SellerName": "Brandon Mckim", "Country": "UK", "City": "Birmingham", "Date": "07/24/2007", "UnitsSold": 307 },
{ "ProductCategory": "Accessories", "UnitPrice": 76.440, "SellerName": "Glenn Landeros", "Country": "Bulgaria", "City": "Plovdiv", "Date": "07/26/2007", "UnitsSold": 445 },
{ "ProductCategory": "Accessories", "UnitPrice": 34.278, "SellerName": "Bryan Culver", "Country": "UK", "City": "London", "Date": "08/01/2007", "UnitsSold": 480 },
{ "ProductCategory": "Clothing", "UnitPrice": 68.573, "SellerName": "Howard Sprouse", "Country": "Japan", "City": "Osaka", "Date": "08/02/2007", "UnitsSold": 390 },
{ "ProductCategory": "Clothing", "UnitPrice": 65.068, "SellerName": "Larry Lieb", "Country": "US", "City": "Chicago", "Date": "08/05/2007", "UnitsSold": 388 },
{ "ProductCategory": "Bikes", "UnitPrice": 44.938, "SellerName": "Russell Shorter", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "08/19/2007", "UnitsSold": 37 },
{ "ProductCategory": "Clothing", "UnitPrice": 93.468, "SellerName": "John Smith", "Country": "US", "City": "Seattle", "Date": "08/24/2007", "UnitsSold": 237 },
{ "ProductCategory": "Accessories", "UnitPrice": 94.365, "SellerName": "Harry Tyler", "Country": "Japan", "City": "Yokohama", "Date": "08/26/2007", "UnitsSold": 396 },
{ "ProductCategory": "Accessories", "UnitPrice": 72.408, "SellerName": "David Haley", "Country": "Uruguay", "City": "Montevideo", "Date": "08/26/2007", "UnitsSold": 3 },
{ "ProductCategory": "Components", "UnitPrice": 80.591, "SellerName": "Russell Shorter", "Country": "Germany", "City": "Berlin", "Date": "09/02/2007", "UnitsSold": 330 },
{ "ProductCategory": "Clothing", "UnitPrice": 65.404, "SellerName": "Benjamin Dupree", "Country": "US", "City": "New York", "Date": "09/04/2007", "UnitsSold": 143 },
{ "ProductCategory": "Components", "UnitPrice": 30.638, "SellerName": "Bryan Culver", "Country": "UK", "City": "Liverpool", "Date": "09/05/2007", "UnitsSold": 318 },
{ "ProductCategory": "Bikes", "UnitPrice": 7.616, "SellerName": "Alfredo Fetuchini", "Country": "Bulgaria", "City": "Plovdiv", "Date": "09/06/2007", "UnitsSold": 393 },
{ "ProductCategory": "Clothing", "UnitPrice": 46.946, "SellerName": "Harold Garvin", "Country": "Germany", "City": "Hamburg", "Date": "09/10/2007", "UnitsSold": 129 },
{ "ProductCategory": "Bikes", "UnitPrice": 38.017, "SellerName": "Glenn Landeros", "Country": "Bulgaria", "City": "Plovdiv", "Date": "09/17/2007", "UnitsSold": 426 },
{ "ProductCategory": "Clothing", "UnitPrice": 2.481, "SellerName": "Harry Tyler", "Country": "Germany", "City": "Hamburg", "Date": "09/18/2007", "UnitsSold": 217 },
{ "ProductCategory": "Accessories", "UnitPrice": 77.589, "SellerName": "John Smith", "Country": "Uruguay", "City": "Montevideo", "Date": "09/20/2007", "UnitsSold": 152 },
{ "ProductCategory": "Components", "UnitPrice": 97.145, "SellerName": "Benjamin Meekins", "Country": "UK", "City": "Liverpool", "Date": "09/25/2007", "UnitsSold": 452 },
{ "ProductCategory": "Clothing", "UnitPrice": 19.697, "SellerName": "Carl Costello", "Country": "US", "City": "Seattle", "Date": "10/02/2007", "UnitsSold": 499 },
{ "ProductCategory": "Accessories", "UnitPrice": 32.775, "SellerName": "Mark Slater", "Country": "UK", "City": "Oxford", "Date": "10/06/2007", "UnitsSold": 169 },
{ "ProductCategory": "Accessories", "UnitPrice": 21.953, "SellerName": "Nicholas Carmona", "Country": "Japan", "City": "Yokohama", "Date": "10/14/2007", "UnitsSold": 386 },
{ "ProductCategory": "Bikes", "UnitPrice": 35.591, "SellerName": "Russell Shorter", "Country": "UK", "City": "Oxford", "Date": "10/14/2007", "UnitsSold": 454 },
{ "ProductCategory": "Bikes", "UnitPrice": 46.950, "SellerName": "Elisa Longbottom", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "10/25/2007", "UnitsSold": 334 },
{ "ProductCategory": "Bikes", "UnitPrice": 41.134, "SellerName": "Lydia Burson", "Country": "US", "City": "Chicago", "Date": "10/26/2007", "UnitsSold": 107 },
{ "ProductCategory": "Clothing", "UnitPrice": 13.837, "SellerName": "Mark Slater", "Country": "US", "City": "Minneapolis", "Date": "11/07/2007", "UnitsSold": 275 },
{ "ProductCategory": "Clothing", "UnitPrice": 64.159, "SellerName": "Monica Freitag", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "11/09/2007", "UnitsSold": 241 },
{ "ProductCategory": "Clothing", "UnitPrice": 1.207, "SellerName": "Larry Lieb", "Country": "Uruguay", "City": "Montevideo", "Date": "11/11/2007", "UnitsSold": 177 },
{ "ProductCategory": "Components", "UnitPrice": 57.805, "SellerName": "Monica Freitag", "Country": "Japan", "City": "Tokyo", "Date": "11/13/2007", "UnitsSold": 494 },
{ "ProductCategory": "Clothing", "UnitPrice": 39.492, "SellerName": "Lydia Burson", "Country": "Bulgaria", "City": "Sofia", "Date": "11/19/2007", "UnitsSold": 451 },
{ "ProductCategory": "Clothing", "UnitPrice": 5.217, "SellerName": "Stanley Brooker", "Country": "Japan", "City": "Osaka", "Date": "01/01/2008", "UnitsSold": 125 },
{ "ProductCategory": "Accessories", "UnitPrice": 53.429, "SellerName": "Kathe Pettel", "Country": "US", "City": "Chicago", "Date": "01/02/2008", "UnitsSold": 103 },
{ "ProductCategory": "Clothing", "UnitPrice": 52.157, "SellerName": "Larry Lieb", "Country": "Japan", "City": "Yokohama", "Date": "01/03/2008", "UnitsSold": 224 },
{ "ProductCategory": "Components", "UnitPrice": 17.694, "SellerName": "Nicholas Carmona", "Country": "Japan", "City": "Yokohama", "Date": "01/07/2008", "UnitsSold": 498 },
{ "ProductCategory": "Bikes", "UnitPrice": 80.741, "SellerName": "Benjamin Dupree", "Country": "Uruguay", "City": "Montevideo", "Date": "01/08/2008", "UnitsSold": 142 },
{ "ProductCategory": "Accessories", "UnitPrice": 95.439, "SellerName": "Larry Lieb", "Country": "US", "City": "Mellvile", "Date": "01/21/2008", "UnitsSold": 487 },
{ "ProductCategory": "Accessories", "UnitPrice": 21.778, "SellerName": "David Haley", "Country": "Bulgaria", "City": "Sofia", "Date": "01/27/2008", "UnitsSold": 331 },
{ "ProductCategory": "Components", "UnitPrice": 29.907, "SellerName": "Glenn Landeros", "Country": "UK", "City": "Liverpool", "Date": "02/03/2008", "UnitsSold": 418 },
{ "ProductCategory": "Accessories", "UnitPrice": 39.839, "SellerName": "Benjamin Meekins", "Country": "Germany", "City": "Berlin", "Date": "02/04/2008", "UnitsSold": 214 },
{ "ProductCategory": "Bikes", "UnitPrice": 40.366, "SellerName": "Elisa Longbottom", "Country": "Japan", "City": "Yokohama", "Date": "02/05/2008", "UnitsSold": 229 },
{ "ProductCategory": "Clothing", "UnitPrice": 35.198, "SellerName": "Alfredo Fetuchini", "Country": "Uruguay", "City": "Montevideo", "Date": "02/05/2008", "UnitsSold": 16 },
{ "ProductCategory": "Accessories", "UnitPrice": 41.755, "SellerName": "Harry Tyler", "Country": "UK", "City": "Cambrige", "Date": "02/08/2008", "UnitsSold": 216 },
{ "ProductCategory": "Accessories", "UnitPrice": 0.687, "SellerName": "Harry Tyler", "Country": "UK", "City": "Cambrige", "Date": "02/09/2008", "UnitsSold": 486 },
{ "ProductCategory": "Accessories", "UnitPrice": 37.556, "SellerName": "Elisa Longbottom", "Country": "Bulgaria", "City": "Plovdiv", "Date": "02/13/2008", "UnitsSold": 172 },
{ "ProductCategory": "Bikes", "UnitPrice": 20.804, "SellerName": "Antonio Charbonneau", "Country": "Germany", "City": "Hamburg", "Date": "02/21/2008", "UnitsSold": 102 },
{ "ProductCategory": "Components", "UnitPrice": 70.646, "SellerName": "Kathe Pettel", "Country": "Japan", "City": "Tokyo", "Date": "02/24/2008", "UnitsSold": 36 },
{ "ProductCategory": "Components", "UnitPrice": 53.290, "SellerName": "Alfredo Fetuchini", "Country": "Uruguay", "City": "Montevideo", "Date": "02/25/2008", "UnitsSold": 71 },
{ "ProductCategory": "Clothing", "UnitPrice": 24.854, "SellerName": "Alfredo Fetuchini", "Country": "Uruguay", "City": "Montevideo", "Date": "02/25/2008", "UnitsSold": 53 },
{ "ProductCategory": "Components", "UnitPrice": 64.632, "SellerName": "Antonio Charbonneau", "Country": "Bulgaria", "City": "Plovdiv", "Date": "02/25/2008", "UnitsSold": 104 },
{ "ProductCategory": "Bikes", "UnitPrice": 9.643, "SellerName": "Brandon Mckim", "Country": "Germany", "City": "Heidelberg", "Date": "02/26/2008", "UnitsSold": 294 },
{ "ProductCategory": "Components", "UnitPrice": 41.077, "SellerName": "Antonio Charbonneau", "Country": "Bulgaria", "City": "Plovdiv", "Date": "03/03/2008", "UnitsSold": 454 },
{ "ProductCategory": "Clothing", "UnitPrice": 36.977, "SellerName": "Stanley Brooker", "Country": "Uruguay", "City": "Montevideo", "Date": "03/05/2008", "UnitsSold": 492 },
{ "ProductCategory": "Components", "UnitPrice": 16.830, "SellerName": "Harry Tyler", "Country": "Japan", "City": "Yokohama", "Date": "03/08/2008", "UnitsSold": 132 },
{ "ProductCategory": "Components", "UnitPrice": 24.716, "SellerName": "Alfredo Fetuchini", "Country": "US", "City": "Lincoln", "Date": "03/09/2008", "UnitsSold": 225 },
{ "ProductCategory": "Components", "UnitPrice": 65.644, "SellerName": "David Haley", "Country": "Germany", "City": "Heidelberg", "Date": "03/10/2008", "UnitsSold": 422 },
{ "ProductCategory": "Components", "UnitPrice": 70.470, "SellerName": "Glenn Landeros", "Country": "Japan", "City": "Yokohama", "Date": "03/12/2008", "UnitsSold": 303 },
{ "ProductCategory": "Accessories", "UnitPrice": 65.117, "SellerName": "Carl Costello", "Country": "US", "City": "Lincoln", "Date": "03/13/2008", "UnitsSold": 319 },
{ "ProductCategory": "Clothing", "UnitPrice": 39.577, "SellerName": "Harold Garvin", "Country": "Bulgaria", "City": "Sofia", "Date": "03/14/2008", "UnitsSold": 262 },
{ "ProductCategory": "Bikes", "UnitPrice": 50.714, "SellerName": "Harold Garvin", "Country": "Germany", "City": "Berlin", "Date": "03/23/2008", "UnitsSold": 345 },
{ "ProductCategory": "Components", "UnitPrice": 88.246, "SellerName": "David Haley", "Country": "Uruguay", "City": "Montevideo", "Date": "04/03/2008", "UnitsSold": 407 },
{ "ProductCategory": "Components", "UnitPrice": 47.252, "SellerName": "Walter Pang", "Country": "US", "City": "New York", "Date": "04/04/2008", "UnitsSold": 121 },
{ "ProductCategory": "Clothing", "UnitPrice": 30.427, "SellerName": "Larry Lieb", "Country": "Uruguay", "City": "Montevideo", "Date": "04/06/2008", "UnitsSold": 30 },
{ "ProductCategory": "Components", "UnitPrice": 88.243, "SellerName": "Harold Garvin", "Country": "US", "City": "Atlanta", "Date": "04/11/2008", "UnitsSold": 293 },
{ "ProductCategory": "Bikes", "UnitPrice": 16.463, "SellerName": "David Haley", "Country": "Bulgaria", "City": "Plovdiv", "Date": "04/12/2008", "UnitsSold": 271 },
{ "ProductCategory": "Clothing", "UnitPrice": 95.208, "SellerName": "Howard Sprouse", "Country": "US", "City": "Mellvile", "Date": "04/18/2008", "UnitsSold": 107 },
{ "ProductCategory": "Components", "UnitPrice": 7.751, "SellerName": "Bryan Culver", "Country": "Japan", "City": "Osaka", "Date": "04/18/2008", "UnitsSold": 87 },
{ "ProductCategory": "Accessories", "UnitPrice": 94.826, "SellerName": "David Haley", "Country": "Germany", "City": "Heidelberg", "Date": "04/23/2008", "UnitsSold": 319 },
{ "ProductCategory": "Clothing", "UnitPrice": 37.211, "SellerName": "Lydia Burson", "Country": "US", "City": "Minneapolis", "Date": "04/24/2008", "UnitsSold": 346 },
{ "ProductCategory": "Clothing", "UnitPrice": 99.308, "SellerName": "Benjamin Dupree", "Country": "US", "City": "Mellvile", "Date": "05/07/2008", "UnitsSold": 382 },
{ "ProductCategory": "Components", "UnitPrice": 96.081, "SellerName": "Larry Lieb", "Country": "Japan", "City": "Yokohama", "Date": "05/11/2008", "UnitsSold": 334 },
{ "ProductCategory": "Clothing", "UnitPrice": 26.152, "SellerName": "Harold Garvin", "Country": "Bulgaria", "City": "Sofia", "Date": "05/13/2008", "UnitsSold": 176 },
{ "ProductCategory": "Components", "UnitPrice": 80.816, "SellerName": "Mark Slater", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "05/19/2008", "UnitsSold": 125 },
{ "ProductCategory": "Accessories", "UnitPrice": 78.320, "SellerName": "Russell Shorter", "Country": "Japan", "City": "Tokyo", "Date": "05/19/2008", "UnitsSold": 458 },
{ "ProductCategory": "Accessories", "UnitPrice": 93.996, "SellerName": "Benjamin Meekins", "Country": "Japan", "City": "Tokyo", "Date": "05/25/2008", "UnitsSold": 331 },
{ "ProductCategory": "Accessories", "UnitPrice": 96.600, "SellerName": "Stanley Brooker", "Country": "Bulgaria", "City": "Plovdiv", "Date": "05/27/2008", "UnitsSold": 39 },
{ "ProductCategory": "Clothing", "UnitPrice": 37.643, "SellerName": "Claudia Kobayashi", "Country": "Uruguay", "City": "Montevideo", "Date": "06/06/2008", "UnitsSold": 238 },
{ "ProductCategory": "Components", "UnitPrice": 46.977, "SellerName": "Walter Pang", "Country": "Japan", "City": "Tokyo", "Date": "06/07/2008", "UnitsSold": 84 },
{ "ProductCategory": "Bikes", "UnitPrice": 80.151, "SellerName": "Mark Slater", "Country": "Germany", "City": "Berlin", "Date": "06/08/2008", "UnitsSold": 363 },
{ "ProductCategory": "Clothing", "UnitPrice": 43.519, "SellerName": "Harry Tyler", "Country": "Germany", "City": "Hamburg", "Date": "06/08/2008", "UnitsSold": 479 },
{ "ProductCategory": "Components", "UnitPrice": 56.316, "SellerName": "Kathe Pettel", "Country": "Uruguay", "City": "Montevideo", "Date": "06/11/2008", "UnitsSold": 404 },
{ "ProductCategory": "Clothing", "UnitPrice": 81.685, "SellerName": "Glenn Landeros", "Country": "Germany", "City": "Heidelberg", "Date": "06/18/2008", "UnitsSold": 478 },
{ "ProductCategory": "Clothing", "UnitPrice": 90.111, "SellerName": "Benjamin Meekins", "Country": "UK", "City": "Liverpool", "Date": "06/19/2008", "UnitsSold": 285 },
{ "ProductCategory": "Bikes", "UnitPrice": 99.342, "SellerName": "Kathe Pettel", "Country": "Bulgaria", "City": "Plovdiv", "Date": "06/22/2008", "UnitsSold": 15 },
{ "ProductCategory": "Clothing", "UnitPrice": 30.834, "SellerName": "Brandon Mckim", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "06/26/2008", "UnitsSold": 245 },
{ "ProductCategory": "Bikes", "UnitPrice": 99.386, "SellerName": "Nicholas Carmona", "Country": "UK", "City": "Oxford", "Date": "07/01/2008", "UnitsSold": 376 },
{ "ProductCategory": "Bikes", "UnitPrice": 73.349, "SellerName": "Claudia Kobayashi", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "07/02/2008", "UnitsSold": 40 },
{ "ProductCategory": "Bikes", "UnitPrice": 43.496, "SellerName": "Larry Lieb", "Country": "UK", "City": "Birmingham", "Date": "07/10/2008", "UnitsSold": 112 },
{ "ProductCategory": "Clothing", "UnitPrice": 16.394, "SellerName": "Antonio Charbonneau", "Country": "Bulgaria", "City": "Plovdiv", "Date": "07/15/2008", "UnitsSold": 224 },
{ "ProductCategory": "Accessories", "UnitPrice": 71.402, "SellerName": "Stanley Brooker", "Country": "Bulgaria", "City": "Sofia", "Date": "07/16/2008", "UnitsSold": 145 },
{ "ProductCategory": "Bikes", "UnitPrice": 94.618, "SellerName": "Stanley Brooker", "Country": "Germany", "City": "Berlin", "Date": "07/21/2008", "UnitsSold": 272 },
{ "ProductCategory": "Components", "UnitPrice": 50.753, "SellerName": "Claudia Kobayashi", "Country": "US", "City": "Seattle", "Date": "07/27/2008", "UnitsSold": 278 },
{ "ProductCategory": "Accessories", "UnitPrice": 12.782, "SellerName": "Harry Tyler", "Country": "Germany", "City": "Heidelberg", "Date": "07/27/2008", "UnitsSold": 253 },
{ "ProductCategory": "Components", "UnitPrice": 35.780, "SellerName": "Nicholas Carmona", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "08/01/2008", "UnitsSold": 255 },
{ "ProductCategory": "Bikes", "UnitPrice": 17.133, "SellerName": "David Haley", "Country": "Bulgaria", "City": "Sofia", "Date": "08/02/2008", "UnitsSold": 46 },
{ "ProductCategory": "Bikes", "UnitPrice": 22.126, "SellerName": "Benjamin Dupree", "Country": "UK", "City": "Birmingham", "Date": "08/08/2008", "UnitsSold": 279 },
{ "ProductCategory": "Accessories", "UnitPrice": 62.986, "SellerName": "Russell Shorter", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "08/08/2008", "UnitsSold": 89 },
{ "ProductCategory": "Clothing", "UnitPrice": 83.838, "SellerName": "Larry Lieb", "Country": "Uruguay", "City": "Montevideo", "Date": "08/14/2008", "UnitsSold": 17 },
{ "ProductCategory": "Bikes", "UnitPrice": 14.075, "SellerName": "Lydia Burson", "Country": "Bulgaria", "City": "Sofia", "Date": "08/21/2008", "UnitsSold": 470 },
{ "ProductCategory": "Bikes", "UnitPrice": 34.591, "SellerName": "Elisa Longbottom", "Country": "UK", "City": "London", "Date": "08/25/2008", "UnitsSold": 195 },
{ "ProductCategory": "Accessories", "UnitPrice": 86.727, "SellerName": "Lydia Burson", "Country": "Germany", "City": "Heidelberg", "Date": "08/27/2008", "UnitsSold": 173 },
{ "ProductCategory": "Accessories", "UnitPrice": 42.236, "SellerName": "Benjamin Dupree", "Country": "UK", "City": "Birmingham", "Date": "09/01/2008", "UnitsSold": 472 },
{ "ProductCategory": "Accessories", "UnitPrice": 25.687, "SellerName": "Larry Lieb", "Country": "Bulgaria", "City": "Sofia", "Date": "09/06/2008", "UnitsSold": 148 },
{ "ProductCategory": "Clothing", "UnitPrice": 23.208, "SellerName": "Walter Pang", "Country": "Germany", "City": "Berlin", "Date": "09/06/2008", "UnitsSold": 314 },
{ "ProductCategory": "Accessories", "UnitPrice": 83.763, "SellerName": "Nicholas Carmona", "Country": "Uruguay", "City": "Montevideo", "Date": "09/07/2008", "UnitsSold": 431 },
{ "ProductCategory": "Clothing", "UnitPrice": 84.414, "SellerName": "Walter Pang", "Country": "Bulgaria", "City": "Plovdiv", "Date": "09/07/2008", "UnitsSold": 347 },
{ "ProductCategory": "Accessories", "UnitPrice": 7.329, "SellerName": "Harry Tyler", "Country": "Uruguay", "City": "Montevideo", "Date": "09/11/2008", "UnitsSold": 27 },
{ "ProductCategory": "Clothing", "UnitPrice": 9.553, "SellerName": "Elisa Longbottom", "Country": "Bulgaria", "City": "Plovdiv", "Date": "09/12/2008", "UnitsSold": 5 },
{ "ProductCategory": "Accessories", "UnitPrice": 50.820, "SellerName": "Larry Lieb", "Country": "Bulgaria", "City": "Plovdiv", "Date": "09/19/2008", "UnitsSold": 191 },
{ "ProductCategory": "Accessories", "UnitPrice": 79.869, "SellerName": "Bryan Culver", "Country": "Bulgaria", "City": "Sofia", "Date": "09/25/2008", "UnitsSold": 421 },
{ "ProductCategory": "Accessories", "UnitPrice": 62.238, "SellerName": "Carl Costello", "Country": "Uruguay", "City": "Montevideo", "Date": "10/03/2008", "UnitsSold": 297 },
{ "ProductCategory": "Clothing", "UnitPrice": 96.094, "SellerName": "Glenn Landeros", "Country": "Japan", "City": "Yokohama", "Date": "10/04/2008", "UnitsSold": 128 },
{ "ProductCategory": "Components", "UnitPrice": 47.009, "SellerName": "Howard Sprouse", "Country": "UK", "City": "Liverpool", "Date": "10/13/2008", "UnitsSold": 210 },
{ "ProductCategory": "Bikes", "UnitPrice": 35.756, "SellerName": "Russell Shorter", "Country": "Japan", "City": "Tokyo", "Date": "10/14/2008", "UnitsSold": 315 },
{ "ProductCategory": "Bikes", "UnitPrice": 78.989, "SellerName": "Benjamin Meekins", "Country": "Japan", "City": "Osaka", "Date": "10/19/2008", "UnitsSold": 489 },
{ "ProductCategory": "Components", "UnitPrice": 84.320, "SellerName": "Walter Pang", "Country": "UK", "City": "Oxford", "Date": "10/21/2008", "UnitsSold": 47 },
{ "ProductCategory": "Accessories", "UnitPrice": 25.528, "SellerName": "John Smith", "Country": "Japan", "City": "Osaka", "Date": "10/22/2008", "UnitsSold": 92 },
{ "ProductCategory": "Bikes", "UnitPrice": 23.874, "SellerName": "Alfredo Fetuchini", "Country": "Germany", "City": "Heidelberg", "Date": "11/01/2008", "UnitsSold": 30 },
{ "ProductCategory": "Accessories", "UnitPrice": 53.634, "SellerName": "Stanley Brooker", "Country": "Bulgaria", "City": "Sofia", "Date": "11/01/2008", "UnitsSold": 132 },
{ "ProductCategory": "Bikes", "UnitPrice": 68.152, "SellerName": "Bryan Culver", "Country": "Japan", "City": "Tokyo", "Date": "11/10/2008", "UnitsSold": 368 },
{ "ProductCategory": "Clothing", "UnitPrice": 59.880, "SellerName": "Kathe Pettel", "Country": "UK", "City": "Oxford", "Date": "11/11/2008", "UnitsSold": 482 },
{ "ProductCategory": "Clothing", "UnitPrice": 5.754, "SellerName": "Antonio Charbonneau", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "11/11/2008", "UnitsSold": 22 },
{ "ProductCategory": "Accessories", "UnitPrice": 95.849, "SellerName": "Claudia Kobayashi", "Country": "UK", "City": "Oxford", "Date": "11/20/2008", "UnitsSold": 159 },
{ "ProductCategory": "Components", "UnitPrice": 59.066, "SellerName": "Alfredo Fetuchini", "Country": "US", "City": "Lincoln", "Date": "11/25/2008", "UnitsSold": 52 },
{ "ProductCategory": "Accessories", "UnitPrice": 94.029, "SellerName": "Harry Tyler", "Country": "Uruguay", "City": "Montevideo", "Date": "01/05/2009", "UnitsSold": 194 },
{ "ProductCategory": "Clothing", "UnitPrice": 12.794, "SellerName": "David Haley", "Country": "UK", "City": "London", "Date": "01/08/2009", "UnitsSold": 100 },
{ "ProductCategory": "Clothing", "UnitPrice": 37.852, "SellerName": "Benjamin Meekins", "Country": "UK", "City": "Oxford", "Date": "01/10/2009", "UnitsSold": 252 },
{ "ProductCategory": "Components", "UnitPrice": 79.434, "SellerName": "Kathe Pettel", "Country": "UK", "City": "Birmingham", "Date": "01/13/2009", "UnitsSold": 116 },
{ "ProductCategory": "Components", "UnitPrice": 90.918, "SellerName": "Elisa Longbottom", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "01/14/2009", "UnitsSold": 259 },
{ "ProductCategory": "Bikes", "UnitPrice": 99.848, "SellerName": "Glenn Landeros", "Country": "Bulgaria", "City": "Sofia", "Date": "01/19/2009", "UnitsSold": 217 },
{ "ProductCategory": "Bikes", "UnitPrice": 43.273, "SellerName": "Bryan Culver", "Country": "Germany", "City": "Hamburg", "Date": "01/22/2009", "UnitsSold": 48 },
{ "ProductCategory": "Clothing", "UnitPrice": 0.654, "SellerName": "Stanley Brooker", "Country": "US", "City": "Mellvile", "Date": "02/02/2009", "UnitsSold": 445 },
{ "ProductCategory": "Clothing", "UnitPrice": 60.464, "SellerName": "Kathe Pettel", "Country": "Bulgaria", "City": "Sofia", "Date": "02/03/2009", "UnitsSold": 90 },
{ "ProductCategory": "Bikes", "UnitPrice": 13.659, "SellerName": "Harry Tyler", "Country": "Uruguay", "City": "Montevideo", "Date": "02/07/2009", "UnitsSold": 453 },
{ "ProductCategory": "Bikes", "UnitPrice": 44.160, "SellerName": "Harry Tyler", "Country": "Japan", "City": "Tokyo", "Date": "02/07/2009", "UnitsSold": 450 },
{ "ProductCategory": "Components", "UnitPrice": 94.330, "SellerName": "Lydia Burson", "Country": "Japan", "City": "Osaka", "Date": "02/07/2009", "UnitsSold": 152 },
{ "ProductCategory": "Accessories", "UnitPrice": 8.783, "SellerName": "Harry Tyler", "Country": "Bulgaria", "City": "Plovdiv", "Date": "02/16/2009", "UnitsSold": 119 },
{ "ProductCategory": "Accessories", "UnitPrice": 79.235, "SellerName": "Kathe Pettel", "Country": "Bulgaria", "City": "Sofia", "Date": "02/16/2009", "UnitsSold": 463 },
{ "ProductCategory": "Bikes", "UnitPrice": 18.588, "SellerName": "Howard Sprouse", "Country": "Germany", "City": "Berlin", "Date": "02/17/2009", "UnitsSold": 150 },
{ "ProductCategory": "Bikes", "UnitPrice": 27.901, "SellerName": "Walter Pang", "Country": "US", "City": "Lincoln", "Date": "02/19/2009", "UnitsSold": 210 },
{ "ProductCategory": "Bikes", "UnitPrice": 67.192, "SellerName": "Kathe Pettel", "Country": "US", "City": "Atlanta", "Date": "02/20/2009", "UnitsSold": 150 },
{ "ProductCategory": "Bikes", "UnitPrice": 35.849, "SellerName": "Benjamin Meekins", "Country": "Bulgaria", "City": "Plovdiv", "Date": "02/21/2009", "UnitsSold": 97 },
{ "ProductCategory": "Bikes", "UnitPrice": 34.073, "SellerName": "Stanley Brooker", "Country": "Japan", "City": "Tokyo", "Date": "02/22/2009", "UnitsSold": 256 },
{ "ProductCategory": "Accessories", "UnitPrice": 66.299, "SellerName": "Russell Shorter", "Country": "US", "City": "Cranbury", "Date": "02/24/2009", "UnitsSold": 172 },
{ "ProductCategory": "Components", "UnitPrice": 14.901, "SellerName": "Monica Freitag", "Country": "Japan", "City": "Tokyo", "Date": "02/24/2009", "UnitsSold": 489 },
{ "ProductCategory": "Bikes", "UnitPrice": 51.915, "SellerName": "Claudia Kobayashi", "Country": "Japan", "City": "Yokohama", "Date": "02/27/2009", "UnitsSold": 222 },
{ "ProductCategory": "Clothing", "UnitPrice": 98.308, "SellerName": "Nicholas Carmona", "Country": "Bulgaria", "City": "Sofia", "Date": "03/03/2009", "UnitsSold": 300 },
{ "ProductCategory": "Bikes", "UnitPrice": 72.820, "SellerName": "Harry Tyler", "Country": "Germany", "City": "Heidelberg", "Date": "03/03/2009", "UnitsSold": 270 },
{ "ProductCategory": "Clothing", "UnitPrice": 16.260, "SellerName": "Claudia Kobayashi", "Country": "US", "City": "Cranbury", "Date": "03/07/2009", "UnitsSold": 263 },
{ "ProductCategory": "Bikes", "UnitPrice": 93.446, "SellerName": "Elisa Longbottom", "Country": "Japan", "City": "Osaka", "Date": "03/10/2009", "UnitsSold": 28 },
{ "ProductCategory": "Components", "UnitPrice": 42.142, "SellerName": "Howard Sprouse", "Country": "Japan", "City": "Yokohama", "Date": "03/15/2009", "UnitsSold": 237 },
{ "ProductCategory": "Accessories", "UnitPrice": 54.983, "SellerName": "Claudia Kobayashi", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "03/16/2009", "UnitsSold": 171 },
{ "ProductCategory": "Components", "UnitPrice": 97.311, "SellerName": "Kathe Pettel", "Country": "Germany", "City": "Hamburg", "Date": "03/27/2009", "UnitsSold": 251 },
{ "ProductCategory": "Components", "UnitPrice": 50.889, "SellerName": "Antonio Charbonneau", "Country": "Bulgaria", "City": "Sofia", "Date": "04/01/2009", "UnitsSold": 275 },
{ "ProductCategory": "Components", "UnitPrice": 4.714, "SellerName": "Brandon Mckim", "Country": "Japan", "City": "Tokyo", "Date": "04/06/2009", "UnitsSold": 311 },
{ "ProductCategory": "Clothing", "UnitPrice": 70.850, "SellerName": "Monica Freitag", "Country": "Japan", "City": "Osaka", "Date": "04/07/2009", "UnitsSold": 217 },
{ "ProductCategory": "Components", "UnitPrice": 96.778, "SellerName": "Claudia Kobayashi", "Country": "Bulgaria", "City": "Sofia", "Date": "04/09/2009", "UnitsSold": 360 },
{ "ProductCategory": "Bikes", "UnitPrice": 83.505, "SellerName": "Howard Sprouse", "Country": "Japan", "City": "Yokohama", "Date": "04/12/2009", "UnitsSold": 35 },
{ "ProductCategory": "Accessories", "UnitPrice": 96.413, "SellerName": "Nicholas Carmona", "Country": "US", "City": "Mellvile", "Date": "04/15/2009", "UnitsSold": 294 },
{ "ProductCategory": "Clothing", "UnitPrice": 70.802, "SellerName": "Howard Sprouse", "Country": "Bulgaria", "City": "Plovdiv", "Date": "04/16/2009", "UnitsSold": 436 },
{ "ProductCategory": "Components", "UnitPrice": 94.524, "SellerName": "Kathe Pettel", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "04/20/2009", "UnitsSold": 78 },
{ "ProductCategory": "Components", "UnitPrice": 29.603, "SellerName": "David Haley", "Country": "US", "City": "Sacramento", "Date": "04/22/2009", "UnitsSold": 301 },
{ "ProductCategory": "Components", "UnitPrice": 70.597, "SellerName": "Mark Slater", "Country": "US", "City": "Chicago", "Date": "05/02/2009", "UnitsSold": 24 },
{ "ProductCategory": "Bikes", "UnitPrice": 71.666, "SellerName": "Howard Sprouse", "Country": "Japan", "City": "Osaka", "Date": "05/04/2009", "UnitsSold": 332 },
{ "ProductCategory": "Components", "UnitPrice": 14.552, "SellerName": "Mark Slater", "Country": "US", "City": "Atlanta", "Date": "05/11/2009", "UnitsSold": 307 },
{ "ProductCategory": "Components", "UnitPrice": 36.712, "SellerName": "Harold Garvin", "Country": "Japan", "City": "Yokohama", "Date": "05/11/2009", "UnitsSold": 375 },
{ "ProductCategory": "Bikes", "UnitPrice": 62.745, "SellerName": "Benjamin Dupree", "Country": "UK", "City": "Cambrige", "Date": "05/12/2009", "UnitsSold": 499 },
{ "ProductCategory": "Accessories", "UnitPrice": 13.699, "SellerName": "Russell Shorter", "Country": "Japan", "City": "Tokyo", "Date": "05/21/2009", "UnitsSold": 337 },
{ "ProductCategory": "Bikes", "UnitPrice": 46.090, "SellerName": "Larry Lieb", "Country": "US", "City": "Sacramento", "Date": "05/24/2009", "UnitsSold": 284 },
{ "ProductCategory": "Clothing", "UnitPrice": 95.336, "SellerName": "Howard Sprouse", "Country": "Bulgaria", "City": "Sofia", "Date": "05/26/2009", "UnitsSold": 292 },
{ "ProductCategory": "Bikes", "UnitPrice": 78.090, "SellerName": "Howard Sprouse", "Country": "Bulgaria", "City": "Sofia", "Date": "05/26/2009", "UnitsSold": 424 },
{ "ProductCategory": "Clothing", "UnitPrice": 99.392, "SellerName": "Mark Slater", "Country": "UK", "City": "Oxford", "Date": "06/05/2009", "UnitsSold": 271 },
{ "ProductCategory": "Components", "UnitPrice": 86.944, "SellerName": "Howard Sprouse", "Country": "Germany", "City": "Heidelberg", "Date": "06/10/2009", "UnitsSold": 6 },
{ "ProductCategory": "Bikes", "UnitPrice": 13.495, "SellerName": "Elisa Longbottom", "Country": "US", "City": "Lincoln", "Date": "06/12/2009", "UnitsSold": 44 },
{ "ProductCategory": "Bikes", "UnitPrice": 99.648, "SellerName": "Nicholas Carmona", "Country": "Japan", "City": "Tokyo", "Date": "06/12/2009", "UnitsSold": 277 },
{ "ProductCategory": "Accessories", "UnitPrice": 16.877, "SellerName": "Brandon Mckim", "Country": "UK", "City": "Cambrige", "Date": "06/13/2009", "UnitsSold": 98 },
{ "ProductCategory": "Components", "UnitPrice": 42.376, "SellerName": "Elisa Longbottom", "Country": "Japan", "City": "Osaka", "Date": "06/22/2009", "UnitsSold": 443 },
{ "ProductCategory": "Clothing", "UnitPrice": 79.539, "SellerName": "Benjamin Dupree", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "06/26/2009", "UnitsSold": 409 },
{ "ProductCategory": "Clothing", "UnitPrice": 26.252, "SellerName": "Walter Pang", "Country": "Bulgaria", "City": "Sofia", "Date": "07/02/2009", "UnitsSold": 240 },
{ "ProductCategory": "Clothing", "UnitPrice": 34.046, "SellerName": "Kathe Pettel", "Country": "UK", "City": "Birmingham", "Date": "07/10/2009", "UnitsSold": 23 },
{ "ProductCategory": "Bikes", "UnitPrice": 29.379, "SellerName": "Larry Lieb", "Country": "Japan", "City": "Tokyo", "Date": "07/12/2009", "UnitsSold": 109 },
{ "ProductCategory": "Accessories", "UnitPrice": 86.650, "SellerName": "Nicholas Carmona", "Country": "Bulgaria", "City": "Sofia", "Date": "07/13/2009", "UnitsSold": 117 },
{ "ProductCategory": "Accessories", "UnitPrice": 58.386, "SellerName": "Mark Slater", "Country": "UK", "City": "Birmingham", "Date": "07/15/2009", "UnitsSold": 336 },
{ "ProductCategory": "Clothing", "UnitPrice": 39.759, "SellerName": "Antonio Charbonneau", "Country": "Germany", "City": "Hamburg", "Date": "07/18/2009", "UnitsSold": 372 },
{ "ProductCategory": "Bikes", "UnitPrice": 10.110, "SellerName": "Larry Lieb", "Country": "Germany", "City": "Hamburg", "Date": "07/19/2009", "UnitsSold": 403 },
{ "ProductCategory": "Accessories", "UnitPrice": 17.772, "SellerName": "Harry Tyler", "Country": "Uruguay", "City": "Montevideo", "Date": "07/19/2009", "UnitsSold": 144 },
{ "ProductCategory": "Clothing", "UnitPrice": 21.543, "SellerName": "Lydia Burson", "Country": "Japan", "City": "Osaka", "Date": "07/19/2009", "UnitsSold": 395 },
{ "ProductCategory": "Clothing", "UnitPrice": 33.561, "SellerName": "Nicholas Carmona", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "07/20/2009", "UnitsSold": 236 },
{ "ProductCategory": "Accessories", "UnitPrice": 48.763, "SellerName": "Larry Lieb", "Country": "Japan", "City": "Osaka", "Date": "07/20/2009", "UnitsSold": 160 },
{ "ProductCategory": "Components", "UnitPrice": 81.797, "SellerName": "David Haley", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "07/20/2009", "UnitsSold": 157 },
{ "ProductCategory": "Components", "UnitPrice": 9.673, "SellerName": "Glenn Landeros", "Country": "Japan", "City": "Tokyo", "Date": "07/25/2009", "UnitsSold": 255 },
{ "ProductCategory": "Bikes", "UnitPrice": 88.575, "SellerName": "Mark Slater", "Country": "Uruguay", "City": "Montevideo", "Date": "08/16/2009", "UnitsSold": 284 },
{ "ProductCategory": "Clothing", "UnitPrice": 89.335, "SellerName": "Walter Pang", "Country": "Bulgaria", "City": "Sofia", "Date": "08/17/2009", "UnitsSold": 333 },
{ "ProductCategory": "Bikes", "UnitPrice": 23.987, "SellerName": "Monica Freitag", "Country": "Japan", "City": "Yokohama", "Date": "08/17/2009", "UnitsSold": 48 },
{ "ProductCategory": "Bikes", "UnitPrice": 19.359, "SellerName": "Kathe Pettel", "Country": "Japan", "City": "Tokyo", "Date": "08/18/2009", "UnitsSold": 399 },
{ "ProductCategory": "Bikes", "UnitPrice": 9.300, "SellerName": "Mark Slater", "Country": "Bulgaria", "City": "Plovdiv", "Date": "08/24/2009", "UnitsSold": 413 },
{ "ProductCategory": "Accessories", "UnitPrice": 1.148, "SellerName": "Monica Freitag", "Country": "UK", "City": "Oxford", "Date": "09/06/2009", "UnitsSold": 182 },
{ "ProductCategory": "Components", "UnitPrice": 76.979, "SellerName": "Russell Shorter", "Country": "Germany", "City": "Heidelberg", "Date": "09/06/2009", "UnitsSold": 156 },
{ "ProductCategory": "Components", "UnitPrice": 80.664, "SellerName": "Antonio Charbonneau", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "09/09/2009", "UnitsSold": 293 },
{ "ProductCategory": "Components", "UnitPrice": 22.788, "SellerName": "Benjamin Dupree", "Country": "UK", "City": "Birmingham", "Date": "10/01/2009", "UnitsSold": 16 },
{ "ProductCategory": "Bikes", "UnitPrice": 78.053, "SellerName": "Benjamin Meekins", "Country": "UK", "City": "Liverpool", "Date": "10/01/2009", "UnitsSold": 106 },
{ "ProductCategory": "Accessories", "UnitPrice": 72.974, "SellerName": "Glenn Landeros", "Country": "Uruguay", "City": "Montevideo", "Date": "10/06/2009", "UnitsSold": 16 },
{ "ProductCategory": "Components", "UnitPrice": 22.058, "SellerName": "John Smith", "Country": "UK", "City": "Birmingham", "Date": "10/07/2009", "UnitsSold": 187 },
{ "ProductCategory": "Bikes", "UnitPrice": 42.791, "SellerName": "Harry Tyler", "Country": "Japan", "City": "Osaka", "Date": "10/10/2009", "UnitsSold": 137 },
{ "ProductCategory": "Clothing", "UnitPrice": 46.231, "SellerName": "Mark Slater", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "10/14/2009", "UnitsSold": 138 },
{ "ProductCategory": "Bikes", "UnitPrice": 14.350, "SellerName": "Mark Slater", "Country": "Bulgaria", "City": "Sofia", "Date": "10/24/2009", "UnitsSold": 256 },
{ "ProductCategory": "Components", "UnitPrice": 40.100, "SellerName": "Antonio Charbonneau", "Country": "Germany", "City": "Hamburg", "Date": "10/24/2009", "UnitsSold": 353 },
{ "ProductCategory": "Accessories", "UnitPrice": 17.189, "SellerName": "Lydia Burson", "Country": "Germany", "City": "Hamburg", "Date": "11/01/2009", "UnitsSold": 359 },
{ "ProductCategory": "Bikes", "UnitPrice": 52.031, "SellerName": "Walter Pang", "Country": "US", "City": "Mellvile", "Date": "11/04/2009", "UnitsSold": 134 },
{ "ProductCategory": "Accessories", "UnitPrice": 90.993, "SellerName": "Larry Lieb", "Country": "UK", "City": "London", "Date": "11/09/2009", "UnitsSold": 263 },
{ "ProductCategory": "Accessories", "UnitPrice": 88.538, "SellerName": "Monica Freitag", "Country": "Germany", "City": "Berlin", "Date": "11/11/2009", "UnitsSold": 313 },
{ "ProductCategory": "Accessories", "UnitPrice": 46.481, "SellerName": "Stanley Brooker", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "11/16/2009", "UnitsSold": 115 },
{ "ProductCategory": "Clothing", "UnitPrice": 20.418, "SellerName": "Claudia Kobayashi", "Country": "US", "City": "New York", "Date": "11/17/2009", "UnitsSold": 414 },
{ "ProductCategory": "Accessories", "UnitPrice": 70.830, "SellerName": "Kathe Pettel", "Country": "Uruguay", "City": "Montevideo", "Date": "11/21/2009", "UnitsSold": 53 },
{ "ProductCategory": "Components", "UnitPrice": 81.628, "SellerName": "John Smith", "Country": "UK", "City": "London", "Date": "11/22/2009", "UnitsSold": 472 },
{ "ProductCategory": "Accessories", "UnitPrice": 9.714, "SellerName": "Harry Tyler", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "11/23/2009", "UnitsSold": 199 },
{ "ProductCategory": "Bikes", "UnitPrice": 29.755, "SellerName": "Harold Garvin", "Country": "US", "City": "Lincoln", "Date": "11/24/2009", "UnitsSold": 241 },
{ "ProductCategory": "Components", "UnitPrice": 33.118, "SellerName": "Glenn Landeros", "Country": "US", "City": "Cranbury", "Date": "11/24/2009", "UnitsSold": 320 },
{ "ProductCategory": "Components", "UnitPrice": 65.635, "SellerName": "David Haley", "Country": "UK", "City": "Liverpool", "Date": "01/02/2010", "UnitsSold": 299 },
{ "ProductCategory": "Accessories", "UnitPrice": 62.085, "SellerName": "Benjamin Dupree", "Country": "Bulgaria", "City": "Plovdiv", "Date": "01/08/2010", "UnitsSold": 366 },
{ "ProductCategory": "Clothing", "UnitPrice": 78.474, "SellerName": "John Smith", "Country": "US", "City": "Mellvile", "Date": "01/10/2010", "UnitsSold": 290 },
{ "ProductCategory": "Accessories", "UnitPrice": 11.587, "SellerName": "Lydia Burson", "Country": "Germany", "City": "Heidelberg", "Date": "01/11/2010", "UnitsSold": 350 },
{ "ProductCategory": "Clothing", "UnitPrice": 33.427, "SellerName": "Russell Shorter", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "01/14/2010", "UnitsSold": 469 },
{ "ProductCategory": "Components", "UnitPrice": 96.141, "SellerName": "Nicholas Carmona", "Country": "UK", "City": "Oxford", "Date": "01/21/2010", "UnitsSold": 352 },
{ "ProductCategory": "Bikes", "UnitPrice": 92.171, "SellerName": "Larry Lieb", "Country": "Bulgaria", "City": "Plovdiv", "Date": "01/25/2010", "UnitsSold": 47 },
{ "ProductCategory": "Bikes", "UnitPrice": 93.045, "SellerName": "Russell Shorter", "Country": "US", "City": "Chicago", "Date": "02/02/2010", "UnitsSold": 153 },
{ "ProductCategory": "Accessories", "UnitPrice": 38.888, "SellerName": "Antonio Charbonneau", "Country": "Germany", "City": "Berlin", "Date": "02/02/2010", "UnitsSold": 211 },
{ "ProductCategory": "Bikes", "UnitPrice": 99.255, "SellerName": "Russell Shorter", "Country": "Japan", "City": "Tokyo", "Date": "02/04/2010", "UnitsSold": 267 },
{ "ProductCategory": "Components", "UnitPrice": 94.418, "SellerName": "Antonio Charbonneau", "Country": "Uruguay", "City": "Montevideo", "Date": "02/04/2010", "UnitsSold": 91 },
{ "ProductCategory": "Accessories", "UnitPrice": 19.770, "SellerName": "Claudia Kobayashi", "Country": "Germany", "City": "Berlin", "Date": "02/05/2010", "UnitsSold": 84 },
{ "ProductCategory": "Components", "UnitPrice": 87.127, "SellerName": "Howard Sprouse", "Country": "US", "City": "Minneapolis", "Date": "02/11/2010", "UnitsSold": 270 },
{ "ProductCategory": "Bikes", "UnitPrice": 76.219, "SellerName": "Alfredo Fetuchini", "Country": "Germany", "City": "Heidelberg", "Date": "02/12/2010", "UnitsSold": 496 },
{ "ProductCategory": "Components", "UnitPrice": 51.935, "SellerName": "John Smith", "Country": "Uruguay", "City": "Montevideo", "Date": "02/16/2010", "UnitsSold": 24 },
{ "ProductCategory": "Components", "UnitPrice": 21.709, "SellerName": "Walter Pang", "Country": "Uruguay", "City": "Montevideo", "Date": "02/17/2010", "UnitsSold": 41 },
{ "ProductCategory": "Bikes", "UnitPrice": 15.665, "SellerName": "John Smith", "Country": "Bulgaria", "City": "Plovdiv", "Date": "02/22/2010", "UnitsSold": 365 },
{ "ProductCategory": "Components", "UnitPrice": 2.677, "SellerName": "Brandon Mckim", "Country": "US", "City": "Minneapolis", "Date": "03/01/2010", "UnitsSold": 202 },
{ "ProductCategory": "Components", "UnitPrice": 52.256, "SellerName": "Howard Sprouse", "Country": "Japan", "City": "Yokohama", "Date": "03/01/2010", "UnitsSold": 225 },
{ "ProductCategory": "Accessories", "UnitPrice": 0.306, "SellerName": "Stanley Brooker", "Country": "Germany", "City": "Hamburg", "Date": "03/03/2010", "UnitsSold": 206 },
{ "ProductCategory": "Accessories", "UnitPrice": 22.362, "SellerName": "Larry Lieb", "Country": "US", "City": "Chicago", "Date": "03/11/2010", "UnitsSold": 158 },
{ "ProductCategory": "Bikes", "UnitPrice": 94.751, "SellerName": "Benjamin Meekins", "Country": "Japan", "City": "Yokohama", "Date": "03/14/2010", "UnitsSold": 169 },
{ "ProductCategory": "Bikes", "UnitPrice": 1.124, "SellerName": "John Smith", "Country": "Japan", "City": "Tokyo", "Date": "03/15/2010", "UnitsSold": 4 },
{ "ProductCategory": "Components", "UnitPrice": 12.168, "SellerName": "Monica Freitag", "Country": "Bulgaria", "City": "Sofia", "Date": "03/15/2010", "UnitsSold": 232 },
{ "ProductCategory": "Bikes", "UnitPrice": 58.754, "SellerName": "Mark Slater", "Country": "Germany", "City": "Heidelberg", "Date": "03/16/2010", "UnitsSold": 421 },
{ "ProductCategory": "Bikes", "UnitPrice": 43.950, "SellerName": "David Haley", "Country": "UK", "City": "Birmingham", "Date": "03/25/2010", "UnitsSold": 260 },
{ "ProductCategory": "Accessories", "UnitPrice": 54.451, "SellerName": "Brandon Mckim", "Country": "Japan", "City": "Tokyo", "Date": "04/02/2010", "UnitsSold": 194 },
{ "ProductCategory": "Components", "UnitPrice": 94.565, "SellerName": "Walter Pang", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "04/05/2010", "UnitsSold": 491 },
{ "ProductCategory": "Accessories", "UnitPrice": 11.121, "SellerName": "Harold Garvin", "Country": "UK", "City": "Liverpool", "Date": "04/14/2010", "UnitsSold": 256 },
{ "ProductCategory": "Components", "UnitPrice": 18.092, "SellerName": "Alfredo Fetuchini", "Country": "US", "City": "Cranbury", "Date": "04/15/2010", "UnitsSold": 279 },
{ "ProductCategory": "Accessories", "UnitPrice": 8.277, "SellerName": "Carl Costello", "Country": "UK", "City": "Oxford", "Date": "04/15/2010", "UnitsSold": 287 },
{ "ProductCategory": "Components", "UnitPrice": 77.894, "SellerName": "Carl Costello", "Country": "Japan", "City": "Yokohama", "Date": "04/22/2010", "UnitsSold": 363 },
{ "ProductCategory": "Clothing", "UnitPrice": 55.624, "SellerName": "Mark Slater", "Country": "Uruguay", "City": "Montevideo", "Date": "04/22/2010", "UnitsSold": 499 },
{ "ProductCategory": "Bikes", "UnitPrice": 39.338, "SellerName": "Lydia Burson", "Country": "Germany", "City": "Hamburg", "Date": "04/24/2010", "UnitsSold": 109 },
{ "ProductCategory": "Components", "UnitPrice": 7.738, "SellerName": "Benjamin Dupree", "Country": "Germany", "City": "Heidelberg", "Date": "05/04/2010", "UnitsSold": 25 },
{ "ProductCategory": "Clothing", "UnitPrice": 62.437, "SellerName": "Alfredo Fetuchini", "Country": "US", "City": "New York", "Date": "05/05/2010", "UnitsSold": 64 },
{ "ProductCategory": "Accessories", "UnitPrice": 38.696, "SellerName": "Howard Sprouse", "Country": "Germany", "City": "Berlin", "Date": "05/06/2010", "UnitsSold": 256 },
{ "ProductCategory": "Bikes", "UnitPrice": 17.764, "SellerName": "Benjamin Meekins", "Country": "Japan", "City": "Osaka", "Date": "05/07/2010", "UnitsSold": 50 },
{ "ProductCategory": "Clothing", "UnitPrice": 57.771, "SellerName": "Bryan Culver", "Country": "Germany", "City": "Heidelberg", "Date": "05/07/2010", "UnitsSold": 437 },
{ "ProductCategory": "Bikes", "UnitPrice": 21.412, "SellerName": "Bryan Culver", "Country": "US", "City": "Chicago", "Date": "05/19/2010", "UnitsSold": 253 },
{ "ProductCategory": "Clothing", "UnitPrice": 10.100, "SellerName": "Monica Freitag", "Country": "US", "City": "Atlanta", "Date": "05/22/2010", "UnitsSold": 312 },
{ "ProductCategory": "Bikes", "UnitPrice": 87.649, "SellerName": "Claudia Kobayashi", "Country": "UK", "City": "London", "Date": "05/24/2010", "UnitsSold": 82 },
{ "ProductCategory": "Clothing", "UnitPrice": 42.552, "SellerName": "Harold Garvin", "Country": "Bulgaria", "City": "Plovdiv", "Date": "06/01/2010", "UnitsSold": 467 },
{ "ProductCategory": "Components", "UnitPrice": 79.772, "SellerName": "Alfredo Fetuchini", "Country": "UK", "City": "Oxford", "Date": "06/05/2010", "UnitsSold": 74 },
{ "ProductCategory": "Components", "UnitPrice": 1.835, "SellerName": "Nicholas Carmona", "Country": "Germany", "City": "Hamburg", "Date": "06/10/2010", "UnitsSold": 81 },
{ "ProductCategory": "Components", "UnitPrice": 15.038, "SellerName": "Kathe Pettel", "Country": "UK", "City": "Liverpool", "Date": "06/25/2010", "UnitsSold": 88 },
{ "ProductCategory": "Accessories", "UnitPrice": 43.393, "SellerName": "Antonio Charbonneau", "Country": "Bulgaria", "City": "Plovdiv", "Date": "06/26/2010", "UnitsSold": 126 },
{ "ProductCategory": "Components", "UnitPrice": 16.236, "SellerName": "Elisa Longbottom", "Country": "US", "City": "Lincoln", "Date": "06/27/2010", "UnitsSold": 112 },
{ "ProductCategory": "Clothing", "UnitPrice": 59.192, "SellerName": "Antonio Charbonneau", "Country": "US", "City": "Chicago", "Date": "06/27/2010", "UnitsSold": 47 },
{ "ProductCategory": "Components", "UnitPrice": 39.858, "SellerName": "Claudia Kobayashi", "Country": "Japan", "City": "Yokohama", "Date": "07/05/2010", "UnitsSold": 218 },
{ "ProductCategory": "Bikes", "UnitPrice": 27.044, "SellerName": "Nicholas Carmona", "Country": "Germany", "City": "Heidelberg", "Date": "07/05/2010", "UnitsSold": 34 },
{ "ProductCategory": "Components", "UnitPrice": 14.269, "SellerName": "Bryan Culver", "Country": "Japan", "City": "Osaka", "Date": "07/13/2010", "UnitsSold": 492 },
{ "ProductCategory": "Clothing", "UnitPrice": 53.378, "SellerName": "Harry Tyler", "Country": "US", "City": "Chicago", "Date": "07/16/2010", "UnitsSold": 464 },
{ "ProductCategory": "Components", "UnitPrice": 21.432, "SellerName": "Harry Tyler", "Country": "Japan", "City": "Yokohama", "Date": "07/17/2010", "UnitsSold": 118 },
{ "ProductCategory": "Bikes", "UnitPrice": 23.970, "SellerName": "Nicholas Carmona", "Country": "Germany", "City": "Berlin", "Date": "07/18/2010", "UnitsSold": 442 },
{ "ProductCategory": "Clothing", "UnitPrice": 37.523, "SellerName": "Benjamin Meekins", "Country": "UK", "City": "Birmingham", "Date": "07/23/2010", "UnitsSold": 248 },
{ "ProductCategory": "Accessories", "UnitPrice": 60.678, "SellerName": "Lydia Burson", "Country": "US", "City": "Atlanta", "Date": "07/23/2010", "UnitsSold": 472 },
{ "ProductCategory": "Bikes", "UnitPrice": 78.023, "SellerName": "Alfredo Fetuchini", "Country": "Germany", "City": "Berlin", "Date": "07/24/2010", "UnitsSold": 140 },
{ "ProductCategory": "Components", "UnitPrice": 47.635, "SellerName": "Lydia Burson", "Country": "Germany", "City": "Hamburg", "Date": "07/26/2010", "UnitsSold": 118 },
{ "ProductCategory": "Components", "UnitPrice": 58.201, "SellerName": "Harry Tyler", "Country": "US", "City": "Atlanta", "Date": "07/27/2010", "UnitsSold": 176 },
{ "ProductCategory": "Clothing", "UnitPrice": 98.375, "SellerName": "Russell Shorter", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "08/01/2010", "UnitsSold": 77 },
{ "ProductCategory": "Components", "UnitPrice": 2.918, "SellerName": "Glenn Landeros", "Country": "Japan", "City": "Tokyo", "Date": "08/08/2010", "UnitsSold": 105 },
{ "ProductCategory": "Components", "UnitPrice": 98.157, "SellerName": "Alfredo Fetuchini", "Country": "Germany", "City": "Hamburg", "Date": "08/21/2010", "UnitsSold": 160 },
{ "ProductCategory": "Bikes", "UnitPrice": 79.036, "SellerName": "Stanley Brooker", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "08/26/2010", "UnitsSold": 186 },
{ "ProductCategory": "Accessories", "UnitPrice": 17.790, "SellerName": "Harold Garvin", "Country": "Japan", "City": "Tokyo", "Date": "09/04/2010", "UnitsSold": 380 },
{ "ProductCategory": "Bikes", "UnitPrice": 38.684, "SellerName": "John Smith", "Country": "US", "City": "Atlanta", "Date": "09/11/2010", "UnitsSold": 470 },
{ "ProductCategory": "Clothing", "UnitPrice": 75.233, "SellerName": "Benjamin Dupree", "Country": "UK", "City": "Liverpool", "Date": "09/13/2010", "UnitsSold": 348 },
{ "ProductCategory": "Components", "UnitPrice": 55.301, "SellerName": "Carl Costello", "Country": "Germany", "City": "Heidelberg", "Date": "09/14/2010", "UnitsSold": 151 },
{ "ProductCategory": "Accessories", "UnitPrice": 51.315, "SellerName": "Kathe Pettel", "Country": "Germany", "City": "Hamburg", "Date": "09/24/2010", "UnitsSold": 7 },
{ "ProductCategory": "Accessories", "UnitPrice": 31.307, "SellerName": "Monica Freitag", "Country": "Japan", "City": "Osaka", "Date": "10/07/2010", "UnitsSold": 123 },
{ "ProductCategory": "Clothing", "UnitPrice": 79.959, "SellerName": "Mark Slater", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "10/08/2010", "UnitsSold": 374 },
{ "ProductCategory": "Clothing", "UnitPrice": 94.657, "SellerName": "Kathe Pettel", "Country": "UK", "City": "Cambrige", "Date": "10/11/2010", "UnitsSold": 178 },
{ "ProductCategory": "Clothing", "UnitPrice": 41.967, "SellerName": "Bryan Culver", "Country": "UK", "City": "London", "Date": "10/22/2010", "UnitsSold": 354 },
{ "ProductCategory": "Accessories", "UnitPrice": 46.564, "SellerName": "Elisa Longbottom", "Country": "US", "City": "Mellvile", "Date": "10/25/2010", "UnitsSold": 459 },
{ "ProductCategory": "Clothing", "UnitPrice": 27.142, "SellerName": "Mark Slater", "Country": "UK", "City": "Birmingham", "Date": "11/02/2010", "UnitsSold": 78 },
{ "ProductCategory": "Bikes", "UnitPrice": 30.232, "SellerName": "Walter Pang", "Country": "Bulgaria", "City": "Plovdiv", "Date": "11/03/2010", "UnitsSold": 417 },
{ "ProductCategory": "Clothing", "UnitPrice": 82.166, "SellerName": "Walter Pang", "Country": "Japan", "City": "Yokohama", "Date": "11/12/2010", "UnitsSold": 208 },
{ "ProductCategory": "Components", "UnitPrice": 13.240, "SellerName": "Harold Garvin", "Country": "Germany", "City": "Heidelberg", "Date": "11/19/2010", "UnitsSold": 359 },
{ "ProductCategory": "Accessories", "UnitPrice": 8.829, "SellerName": "Russell Shorter", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "11/25/2010", "UnitsSold": 392 },
{ "ProductCategory": "Clothing", "UnitPrice": 78.426, "SellerName": "John Smith", "Country": "Bulgaria", "City": "Plovdiv", "Date": "01/01/2011", "UnitsSold": 241 },
{ "ProductCategory": "Clothing", "UnitPrice": 50.590, "SellerName": "Claudia Kobayashi", "Country": "UK", "City": "Liverpool", "Date": "01/04/2011", "UnitsSold": 62 },
{ "ProductCategory": "Bikes", "UnitPrice": 6.307, "SellerName": "Elisa Longbottom", "Country": "Uruguay", "City": "Montevideo", "Date": "01/06/2011", "UnitsSold": 485 },
{ "ProductCategory": "Bikes", "UnitPrice": 47.444, "SellerName": "Bryan Culver", "Country": "Japan", "City": "Tokyo", "Date": "01/14/2011", "UnitsSold": 470 },
{ "ProductCategory": "Bikes", "UnitPrice": 6.147, "SellerName": "Harry Tyler", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "01/23/2011", "UnitsSold": 197 },
{ "ProductCategory": "Clothing", "UnitPrice": 57.598, "SellerName": "Larry Lieb", "Country": "Germany", "City": "Heidelberg", "Date": "01/26/2011", "UnitsSold": 353 },
{ "ProductCategory": "Components", "UnitPrice": 37.619, "SellerName": "Benjamin Meekins", "Country": "US", "City": "Chicago", "Date": "02/01/2011", "UnitsSold": 338 },
{ "ProductCategory": "Clothing", "UnitPrice": 20.995, "SellerName": "Claudia Kobayashi", "Country": "Japan", "City": "Yokohama", "Date": "02/08/2011", "UnitsSold": 17 },
{ "ProductCategory": "Clothing", "UnitPrice": 11.776, "SellerName": "Antonio Charbonneau", "Country": "US", "City": "Sacramento", "Date": "02/12/2011", "UnitsSold": 429 },
{ "ProductCategory": "Components", "UnitPrice": 64.996, "SellerName": "Alfredo Fetuchini", "Country": "Germany", "City": "Berlin", "Date": "02/14/2011", "UnitsSold": 385 },
{ "ProductCategory": "Clothing", "UnitPrice": 19.899, "SellerName": "Claudia Kobayashi", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "02/20/2011", "UnitsSold": 166 },
{ "ProductCategory": "Components", "UnitPrice": 3.243, "SellerName": "Lydia Burson", "Country": "Bulgaria", "City": "Sofia", "Date": "02/20/2011", "UnitsSold": 137 },
{ "ProductCategory": "Bikes", "UnitPrice": 18.180, "SellerName": "Russell Shorter", "Country": "Germany", "City": "Berlin", "Date": "02/24/2011", "UnitsSold": 443 },
{ "ProductCategory": "Bikes", "UnitPrice": 20.442, "SellerName": "Carl Costello", "Country": "Bulgaria", "City": "Sofia", "Date": "02/26/2011", "UnitsSold": 40 },
{ "ProductCategory": "Bikes", "UnitPrice": 20.547, "SellerName": "Glenn Landeros", "Country": "Germany", "City": "Heidelberg", "Date": "03/05/2011", "UnitsSold": 138 },
{ "ProductCategory": "Clothing", "UnitPrice": 23.766, "SellerName": "Lydia Burson", "Country": "US", "City": "Mellvile", "Date": "03/09/2011", "UnitsSold": 15 },
{ "ProductCategory": "Clothing", "UnitPrice": 76.253, "SellerName": "Antonio Charbonneau", "Country": "Japan", "City": "Osaka", "Date": "03/09/2011", "UnitsSold": 469 },
{ "ProductCategory": "Clothing", "UnitPrice": 93.251, "SellerName": "Russell Shorter", "Country": "UK", "City": "Oxford", "Date": "03/11/2011", "UnitsSold": 426 },
{ "ProductCategory": "Components", "UnitPrice": 62.992, "SellerName": "Benjamin Dupree", "Country": "Japan", "City": "Osaka", "Date": "03/16/2011", "UnitsSold": 208 },
{ "ProductCategory": "Clothing", "UnitPrice": 58.498, "SellerName": "Brandon Mckim", "Country": "Germany", "City": "Heidelberg", "Date": "03/21/2011", "UnitsSold": 155 },
{ "ProductCategory": "Clothing", "UnitPrice": 82.383, "SellerName": "Stanley Brooker", "Country": "Japan", "City": "Tokyo", "Date": "03/23/2011", "UnitsSold": 381 },
{ "ProductCategory": "Components", "UnitPrice": 19.168, "SellerName": "Nicholas Carmona", "Country": "Bulgaria", "City": "Plovdiv", "Date": "04/12/2011", "UnitsSold": 5 },
{ "ProductCategory": "Clothing", "UnitPrice": 53.516, "SellerName": "Walter Pang", "Country": "UK", "City": "Cambrige", "Date": "04/12/2011", "UnitsSold": 221 },
{ "ProductCategory": "Accessories", "UnitPrice": 97.407, "SellerName": "Howard Sprouse", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "04/14/2011", "UnitsSold": 39 },
{ "ProductCategory": "Bikes", "UnitPrice": 74.054, "SellerName": "Mark Slater", "Country": "Bulgaria", "City": "Sofia", "Date": "04/16/2011", "UnitsSold": 468 },
{ "ProductCategory": "Accessories", "UnitPrice": 8.104, "SellerName": "Claudia Kobayashi", "Country": "Bulgaria", "City": "Sofia", "Date": "04/17/2011", "UnitsSold": 44 },
{ "ProductCategory": "Clothing", "UnitPrice": 59.055, "SellerName": "John Smith", "Country": "UK", "City": "Oxford", "Date": "04/22/2011", "UnitsSold": 287 },
{ "ProductCategory": "Accessories", "UnitPrice": 96.816, "SellerName": "Russell Shorter", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "04/24/2011", "UnitsSold": 463 },
{ "ProductCategory": "Components", "UnitPrice": 76.712, "SellerName": "Walter Pang", "Country": "Uruguay", "City": "Montevideo", "Date": "04/24/2011", "UnitsSold": 335 },
{ "ProductCategory": "Accessories", "UnitPrice": 73.424, "SellerName": "Walter Pang", "Country": "US", "City": "Lincoln", "Date": "04/24/2011", "UnitsSold": 211 },
{ "ProductCategory": "Components", "UnitPrice": 66.398, "SellerName": "Benjamin Dupree", "Country": "US", "City": "Sacramento", "Date": "05/03/2011", "UnitsSold": 291 },
{ "ProductCategory": "Clothing", "UnitPrice": 37.014, "SellerName": "John Smith", "Country": "US", "City": "Chicago", "Date": "05/05/2011", "UnitsSold": 1 },
{ "ProductCategory": "Clothing", "UnitPrice": 21.307, "SellerName": "Alfredo Fetuchini", "Country": "UK", "City": "Liverpool", "Date": "05/06/2011", "UnitsSold": 120 },
{ "ProductCategory": "Bikes", "UnitPrice": 19.893, "SellerName": "Benjamin Dupree", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "05/06/2011", "UnitsSold": 382 },
{ "ProductCategory": "Clothing", "UnitPrice": 16.486, "SellerName": "Harry Tyler", "Country": "Japan", "City": "Tokyo", "Date": "05/07/2011", "UnitsSold": 63 },
{ "ProductCategory": "Clothing", "UnitPrice": 41.660, "SellerName": "Stanley Brooker", "Country": "Germany", "City": "Hamburg", "Date": "05/12/2011", "UnitsSold": 230 },
{ "ProductCategory": "Components", "UnitPrice": 4.977, "SellerName": "Larry Lieb", "Country": "Japan", "City": "Osaka", "Date": "05/13/2011", "UnitsSold": 362 },
{ "ProductCategory": "Components", "UnitPrice": 10.749, "SellerName": "Monica Freitag", "Country": "Germany", "City": "Hamburg", "Date": "05/17/2011", "UnitsSold": 430 },
{ "ProductCategory": "Bikes", "UnitPrice": 66.047, "SellerName": "Nicholas Carmona", "Country": "Germany", "City": "Berlin", "Date": "05/23/2011", "UnitsSold": 204 },
{ "ProductCategory": "Bikes", "UnitPrice": 60.848, "SellerName": "Antonio Charbonneau", "Country": "Uruguay", "City": "Montevideo", "Date": "05/24/2011", "UnitsSold": 118 },
{ "ProductCategory": "Accessories", "UnitPrice": 68.708, "SellerName": "Walter Pang", "Country": "US", "City": "New York", "Date": "06/01/2011", "UnitsSold": 17 },
{ "ProductCategory": "Components", "UnitPrice": 40.680, "SellerName": "Walter Pang", "Country": "UK", "City": "London", "Date": "06/03/2011", "UnitsSold": 312 },
{ "ProductCategory": "Accessories", "UnitPrice": 96.900, "SellerName": "Lydia Burson", "Country": "Japan", "City": "Tokyo", "Date": "06/12/2011", "UnitsSold": 283 },
{ "ProductCategory": "Components", "UnitPrice": 67.031, "SellerName": "Benjamin Dupree", "Country": "Germany", "City": "Berlin", "Date": "06/13/2011", "UnitsSold": 460 },
{ "ProductCategory": "Bikes", "UnitPrice": 67.092, "SellerName": "Howard Sprouse", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "06/14/2011", "UnitsSold": 295 },
{ "ProductCategory": "Bikes", "UnitPrice": 28.048, "SellerName": "Alfredo Fetuchini", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "06/15/2011", "UnitsSold": 49 },
{ "ProductCategory": "Bikes", "UnitPrice": 7.383, "SellerName": "Russell Shorter", "Country": "Germany", "City": "Berlin", "Date": "06/24/2011", "UnitsSold": 127 },
{ "ProductCategory": "Components", "UnitPrice": 39.219, "SellerName": "Mark Slater", "Country": "UK", "City": "Birmingham", "Date": "06/27/2011", "UnitsSold": 244 },
{ "ProductCategory": "Accessories", "UnitPrice": 53.418, "SellerName": "Harold Garvin", "Country": "Japan", "City": "Osaka", "Date": "07/01/2011", "UnitsSold": 188 },
{ "ProductCategory": "Bikes", "UnitPrice": 25.523, "SellerName": "Benjamin Dupree", "Country": "Germany", "City": "Hamburg", "Date": "07/06/2011", "UnitsSold": 458 },
{ "ProductCategory": "Components", "UnitPrice": 70.257, "SellerName": "Nicholas Carmona", "Country": "US", "City": "Chicago", "Date": "07/08/2011", "UnitsSold": 448 },
{ "ProductCategory": "Bikes", "UnitPrice": 7.636, "SellerName": "Harold Garvin", "Country": "Bulgaria", "City": "Sofia", "Date": "07/27/2011", "UnitsSold": 226 },
{ "ProductCategory": "Components", "UnitPrice": 21.512, "SellerName": "Benjamin Dupree", "Country": "Japan", "City": "Osaka", "Date": "08/01/2011", "UnitsSold": 474 },
{ "ProductCategory": "Accessories", "UnitPrice": 37.596, "SellerName": "David Haley", "Country": "US", "City": "Minneapolis", "Date": "08/02/2011", "UnitsSold": 338 },
{ "ProductCategory": "Components", "UnitPrice": 99.364, "SellerName": "Benjamin Meekins", "Country": "Bulgaria", "City": "Sofia", "Date": "08/02/2011", "UnitsSold": 88 },
{ "ProductCategory": "Bikes", "UnitPrice": 72.232, "SellerName": "Carl Costello", "Country": "Bulgaria", "City": "Plovdiv", "Date": "08/04/2011", "UnitsSold": 436 },
{ "ProductCategory": "Clothing", "UnitPrice": 34.253, "SellerName": "Nicholas Carmona", "Country": "Bulgaria", "City": "Sofia", "Date": "08/06/2011", "UnitsSold": 297 },
{ "ProductCategory": "Accessories", "UnitPrice": 46.885, "SellerName": "Russell Shorter", "Country": "Bulgaria", "City": "Sofia", "Date": "08/07/2011", "UnitsSold": 240 },
{ "ProductCategory": "Bikes", "UnitPrice": 26.369, "SellerName": "Stanley Brooker", "Country": "Bulgaria", "City": "Sofia", "Date": "08/07/2011", "UnitsSold": 415 },
{ "ProductCategory": "Accessories", "UnitPrice": 49.072, "SellerName": "David Haley", "Country": "US", "City": "Cranbury", "Date": "08/08/2011", "UnitsSold": 435 },
{ "ProductCategory": "Bikes", "UnitPrice": 95.058, "SellerName": "Monica Freitag", "Country": "UK", "City": "Oxford", "Date": "08/16/2011", "UnitsSold": 64 },
{ "ProductCategory": "Clothing", "UnitPrice": 74.181, "SellerName": "John Smith", "Country": "Japan", "City": "Tokyo", "Date": "08/23/2011", "UnitsSold": 21 },
{ "ProductCategory": "Clothing", "UnitPrice": 82.506, "SellerName": "Benjamin Dupree", "Country": "UK", "City": "Liverpool", "Date": "08/25/2011", "UnitsSold": 467 },
{ "ProductCategory": "Bikes", "UnitPrice": 42.773, "SellerName": "Lydia Burson", "Country": "Japan", "City": "Yokohama", "Date": "09/02/2011", "UnitsSold": 98 },
{ "ProductCategory": "Components", "UnitPrice": 83.472, "SellerName": "Russell Shorter", "Country": "US", "City": "Atlanta", "Date": "09/04/2011", "UnitsSold": 370 },
{ "ProductCategory": "Bikes", "UnitPrice": 41.552, "SellerName": "Walter Pang", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "09/05/2011", "UnitsSold": 94 },
{ "ProductCategory": "Components", "UnitPrice": 74.118, "SellerName": "Benjamin Dupree", "Country": "Germany", "City": "Hamburg", "Date": "09/09/2011", "UnitsSold": 106 },
{ "ProductCategory": "Bikes", "UnitPrice": 75.404, "SellerName": "Claudia Kobayashi", "Country": "Germany", "City": "Berlin", "Date": "09/11/2011", "UnitsSold": 261 },
{ "ProductCategory": "Clothing", "UnitPrice": 10.227, "SellerName": "Howard Sprouse", "Country": "Uruguay", "City": "Montevideo", "Date": "09/17/2011", "UnitsSold": 307 },
{ "ProductCategory": "Bikes", "UnitPrice": 72.929, "SellerName": "Harry Tyler", "Country": "US", "City": "New York", "Date": "09/17/2011", "UnitsSold": 362 },
{ "ProductCategory": "Bikes", "UnitPrice": 85.133, "SellerName": "Benjamin Meekins", "Country": "Uruguay", "City": "Montevideo", "Date": "09/24/2011", "UnitsSold": 330 },
{ "ProductCategory": "Components", "UnitPrice": 77.595, "SellerName": "Walter Pang", "Country": "UK", "City": "Oxford", "Date": "09/26/2011", "UnitsSold": 23 },
{ "ProductCategory": "Accessories", "UnitPrice": 50.362, "SellerName": "David Haley", "Country": "Japan", "City": "Tokyo", "Date": "09/27/2011", "UnitsSold": 392 },
{ "ProductCategory": "Bikes", "UnitPrice": 32.290, "SellerName": "Larry Lieb", "Country": "Japan", "City": "Tokyo", "Date": "10/13/2011", "UnitsSold": 16 },
{ "ProductCategory": "Clothing", "UnitPrice": 62.986, "SellerName": "Lydia Burson", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "10/13/2011", "UnitsSold": 100 },
{ "ProductCategory": "Bikes", "UnitPrice": 13.441, "SellerName": "Carl Costello", "Country": "UK", "City": "Cambrige", "Date": "10/22/2011", "UnitsSold": 132 },
{ "ProductCategory": "Bikes", "UnitPrice": 0.361, "SellerName": "Nicholas Carmona", "Country": "US", "City": "Seattle", "Date": "10/22/2011", "UnitsSold": 22 },
{ "ProductCategory": "Bikes", "UnitPrice": 66.237, "SellerName": "Walter Pang", "Country": "Bulgaria", "City": "Plovdiv", "Date": "11/02/2011", "UnitsSold": 96 },
{ "ProductCategory": "Accessories", "UnitPrice": 50.146, "SellerName": "Elisa Longbottom", "Country": "Germany", "City": "Berlin", "Date": "11/03/2011", "UnitsSold": 76 },
{ "ProductCategory": "Bikes", "UnitPrice": 67.883, "SellerName": "Stanley Brooker", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "11/04/2011", "UnitsSold": 492 },
{ "ProductCategory": "Clothing", "UnitPrice": 6.553, "SellerName": "Harry Tyler", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "11/08/2011", "UnitsSold": 49 },
{ "ProductCategory": "Components", "UnitPrice": 35.553, "SellerName": "Russell Shorter", "Country": "Bulgaria", "City": "Plovdiv", "Date": "11/12/2011", "UnitsSold": 197 },
{ "ProductCategory": "Accessories", "UnitPrice": 59.927, "SellerName": "Howard Sprouse", "Country": "UK", "City": "Birmingham", "Date": "11/12/2011", "UnitsSold": 484 },
{ "ProductCategory": "Bikes", "UnitPrice": 67.355, "SellerName": "Russell Shorter", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "11/13/2011", "UnitsSold": 182 },
{ "ProductCategory": "Accessories", "UnitPrice": 51.975, "SellerName": "Alfredo Fetuchini", "Country": "Japan", "City": "Osaka", "Date": "11/15/2011", "UnitsSold": 42 },
{ "ProductCategory": "Clothing", "UnitPrice": 66.674, "SellerName": "Brandon Mckim", "Country": "Germany", "City": "Heidelberg", "Date": "11/19/2011", "UnitsSold": 109 },
{ "ProductCategory": "Bikes", "UnitPrice": 56.137, "SellerName": "Harold Garvin", "Country": "Uruguay", "City": "Montevideo", "Date": "11/23/2011", "UnitsSold": 310 },
{ "ProductCategory": "Clothing", "UnitPrice": 93.530, "SellerName": "Monica Freitag", "Country": "Bulgaria", "City": "Sofia", "Date": "01/03/2012", "UnitsSold": 306 },
{ "ProductCategory": "Components", "UnitPrice": 9.533, "SellerName": "Harold Garvin", "Country": "Germany", "City": "Heidelberg", "Date": "01/06/2012", "UnitsSold": 290 },
{ "ProductCategory": "Components", "UnitPrice": 41.117, "SellerName": "Monica Freitag", "Country": "US", "City": "Cranbury", "Date": "01/10/2012", "UnitsSold": 499 },
{ "ProductCategory": "Clothing", "UnitPrice": 9.799, "SellerName": "Kathe Pettel", "Country": "UK", "City": "Cambrige", "Date": "01/11/2012", "UnitsSold": 7 },
{ "ProductCategory": "Components", "UnitPrice": 64.580, "SellerName": "Nicholas Carmona", "Country": "Japan", "City": "Yokohama", "Date": "01/14/2012", "UnitsSold": 220 },
{ "ProductCategory": "Components", "UnitPrice": 47.282, "SellerName": "Elisa Longbottom", "Country": "Bulgaria", "City": "Sofia", "Date": "01/15/2012", "UnitsSold": 395 },
{ "ProductCategory": "Clothing", "UnitPrice": 14.609, "SellerName": "Lydia Burson", "Country": "UK", "City": "Liverpool", "Date": "01/18/2012", "UnitsSold": 219 },
{ "ProductCategory": "Components", "UnitPrice": 10.681, "SellerName": "Larry Lieb", "Country": "Germany", "City": "Heidelberg", "Date": "01/18/2012", "UnitsSold": 229 },
{ "ProductCategory": "Components", "UnitPrice": 64.914, "SellerName": "Nicholas Carmona", "Country": "Japan", "City": "Osaka", "Date": "01/22/2012", "UnitsSold": 111 },
{ "ProductCategory": "Bikes", "UnitPrice": 47.909, "SellerName": "Alfredo Fetuchini", "Country": "UK", "City": "Cambrige", "Date": "02/01/2012", "UnitsSold": 237 },
{ "ProductCategory": "Bikes", "UnitPrice": 87.815, "SellerName": "Claudia Kobayashi", "Country": "Bulgaria", "City": "Sofia", "Date": "02/13/2012", "UnitsSold": 114 },
{ "ProductCategory": "Clothing", "UnitPrice": 55.404, "SellerName": "Bryan Culver", "Country": "Uruguay", "City": "Montevideo", "Date": "02/23/2012", "UnitsSold": 329 },
{ "ProductCategory": "Clothing", "UnitPrice": 40.755, "SellerName": "Howard Sprouse", "Country": "US", "City": "Sacramento", "Date": "02/24/2012", "UnitsSold": 135 },
{ "ProductCategory": "Bikes", "UnitPrice": 57.827, "SellerName": "Harold Garvin", "Country": "UK", "City": "London", "Date": "03/02/2012", "UnitsSold": 187 },
{ "ProductCategory": "Components", "UnitPrice": 14.764, "SellerName": "David Haley", "Country": "Germany", "City": "Heidelberg", "Date": "03/10/2012", "UnitsSold": 286 },
{ "ProductCategory": "Accessories", "UnitPrice": 12.991, "SellerName": "Antonio Charbonneau", "Country": "US", "City": "Sacramento", "Date": "03/11/2012", "UnitsSold": 468 },
{ "ProductCategory": "Components", "UnitPrice": 26.013, "SellerName": "Monica Freitag", "Country": "Germany", "City": "Heidelberg", "Date": "03/18/2012", "UnitsSold": 71 },
{ "ProductCategory": "Bikes", "UnitPrice": 72.623, "SellerName": "Bryan Culver", "Country": "Germany", "City": "Heidelberg", "Date": "03/21/2012", "UnitsSold": 251 },
{ "ProductCategory": "Accessories", "UnitPrice": 44.430, "SellerName": "Monica Freitag", "Country": "Bulgaria", "City": "Plovdiv", "Date": "03/25/2012", "UnitsSold": 297 },
{ "ProductCategory": "Bikes", "UnitPrice": 68.192, "SellerName": "Alfredo Fetuchini", "Country": "Japan", "City": "Osaka", "Date": "03/25/2012", "UnitsSold": 248 },
{ "ProductCategory": "Components", "UnitPrice": 35.301, "SellerName": "Elisa Longbottom", "Country": "Japan", "City": "Yokohama", "Date": "03/26/2012", "UnitsSold": 488 },
{ "ProductCategory": "Clothing", "UnitPrice": 41.079, "SellerName": "Alfredo Fetuchini", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "04/06/2012", "UnitsSold": 211 },
{ "ProductCategory": "Components", "UnitPrice": 29.287, "SellerName": "Stanley Brooker", "Country": "Japan", "City": "Osaka", "Date": "04/14/2012", "UnitsSold": 149 },
{ "ProductCategory": "Accessories", "UnitPrice": 51.960, "SellerName": "Lydia Burson", "Country": "Bulgaria", "City": "Sofia", "Date": "04/14/2012", "UnitsSold": 99 },
{ "ProductCategory": "Components", "UnitPrice": 57.838, "SellerName": "Benjamin Meekins", "Country": "Bulgaria", "City": "Plovdiv", "Date": "04/16/2012", "UnitsSold": 225 },
{ "ProductCategory": "Components", "UnitPrice": 25.879, "SellerName": "Nicholas Carmona", "Country": "UK", "City": "Oxford", "Date": "04/27/2012", "UnitsSold": 408 },
{ "ProductCategory": "Components", "UnitPrice": 4.930, "SellerName": "Benjamin Meekins", "Country": "Germany", "City": "Berlin", "Date": "05/09/2012", "UnitsSold": 417 },
{ "ProductCategory": "Clothing", "UnitPrice": 3.035, "SellerName": "Alfredo Fetuchini", "Country": "US", "City": "Cranbury", "Date": "05/24/2012", "UnitsSold": 221 },
{ "ProductCategory": "Accessories", "UnitPrice": 57.525, "SellerName": "Mark Slater", "Country": "US", "City": "Chicago", "Date": "06/02/2012", "UnitsSold": 288 },
{ "ProductCategory": "Components", "UnitPrice": 72.260, "SellerName": "Bryan Culver", "Country": "US", "City": "Cranbury", "Date": "06/03/2012", "UnitsSold": 372 },
{ "ProductCategory": "Accessories", "UnitPrice": 82.533, "SellerName": "Kathe Pettel", "Country": "Japan", "City": "Tokyo", "Date": "06/03/2012", "UnitsSold": 408 },
{ "ProductCategory": "Clothing", "UnitPrice": 91.596, "SellerName": "Benjamin Dupree", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "06/04/2012", "UnitsSold": 13 },
{ "ProductCategory": "Components", "UnitPrice": 94.668, "SellerName": "Benjamin Dupree", "Country": "Bulgaria", "City": "Plovdiv", "Date": "06/05/2012", "UnitsSold": 487 },
{ "ProductCategory": "Clothing", "UnitPrice": 46.269, "SellerName": "Benjamin Dupree", "Country": "Uruguay", "City": "Montevideo", "Date": "06/11/2012", "UnitsSold": 276 },
{ "ProductCategory": "Bikes", "UnitPrice": 18.243, "SellerName": "Howard Sprouse", "Country": "UK", "City": "Oxford", "Date": "06/16/2012", "UnitsSold": 490 },
{ "ProductCategory": "Components", "UnitPrice": 48.753, "SellerName": "Harold Garvin", "Country": "Japan", "City": "Tokyo", "Date": "06/18/2012", "UnitsSold": 238 },
{ "ProductCategory": "Components", "UnitPrice": 94.427, "SellerName": "David Haley", "Country": "Bulgaria", "City": "Sofia", "Date": "06/23/2012", "UnitsSold": 170 },
{ "ProductCategory": "Accessories", "UnitPrice": 48.675, "SellerName": "Brandon Mckim", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "07/04/2012", "UnitsSold": 132 },
{ "ProductCategory": "Bikes", "UnitPrice": 82.680, "SellerName": "Mark Slater", "Country": "Bulgaria", "City": "Sofia", "Date": "07/05/2012", "UnitsSold": 443 },
{ "ProductCategory": "Bikes", "UnitPrice": 38.192, "SellerName": "Benjamin Dupree", "Country": "Germany", "City": "Hamburg", "Date": "07/05/2012", "UnitsSold": 368 },
{ "ProductCategory": "Bikes", "UnitPrice": 24.194, "SellerName": "Harold Garvin", "Country": "US", "City": "Chicago", "Date": "07/11/2012", "UnitsSold": 39 },
{ "ProductCategory": "Bikes", "UnitPrice": 3.989, "SellerName": "Alfredo Fetuchini", "Country": "Bulgaria", "City": "Plovdiv", "Date": "07/13/2012", "UnitsSold": 95 },
{ "ProductCategory": "Clothing", "UnitPrice": 81.770, "SellerName": "Benjamin Meekins", "Country": "Japan", "City": "Osaka", "Date": "07/14/2012", "UnitsSold": 42 },
{ "ProductCategory": "Bikes", "UnitPrice": 74.867, "SellerName": "Brandon Mckim", "Country": "Japan", "City": "Tokyo", "Date": "07/16/2012", "UnitsSold": 200 },
{ "ProductCategory": "Components", "UnitPrice": 85.467, "SellerName": "Monica Freitag", "Country": "Germany", "City": "Heidelberg", "Date": "07/16/2012", "UnitsSold": 221 },
{ "ProductCategory": "Clothing", "UnitPrice": 96.415, "SellerName": "Larry Lieb", "Country": "US", "City": "Cranbury", "Date": "07/21/2012", "UnitsSold": 54 },
{ "ProductCategory": "Clothing", "UnitPrice": 46.199, "SellerName": "Lydia Burson", "Country": "Bulgaria", "City": "Plovdiv", "Date": "07/21/2012", "UnitsSold": 173 },
{ "ProductCategory": "Accessories", "UnitPrice": 99.843, "SellerName": "Lydia Burson", "Country": "UK", "City": "Oxford", "Date": "07/23/2012", "UnitsSold": 47 },
{ "ProductCategory": "Bikes", "UnitPrice": 42.354, "SellerName": "Kathe Pettel", "Country": "US", "City": "Chicago", "Date": "07/26/2012", "UnitsSold": 173 },
{ "ProductCategory": "Bikes", "UnitPrice": 52.198, "SellerName": "Claudia Kobayashi", "Country": "Germany", "City": "Berlin", "Date": "08/05/2012", "UnitsSold": 323 },
{ "ProductCategory": "Components", "UnitPrice": 45.456, "SellerName": "Russell Shorter", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "08/07/2012", "UnitsSold": 264 },
{ "ProductCategory": "Accessories", "UnitPrice": 56.771, "SellerName": "Mark Slater", "Country": "Japan", "City": "Tokyo", "Date": "08/09/2012", "UnitsSold": 385 },
{ "ProductCategory": "Bikes", "UnitPrice": 3.565, "SellerName": "Harry Tyler", "Country": "Bulgaria", "City": "Sofia", "Date": "08/10/2012", "UnitsSold": 56 },
{ "ProductCategory": "Bikes", "UnitPrice": 34.601, "SellerName": "Benjamin Dupree", "Country": "Germany", "City": "Berlin", "Date": "08/12/2012", "UnitsSold": 267 },
{ "ProductCategory": "Accessories", "UnitPrice": 92.402, "SellerName": "Monica Freitag", "Country": "US", "City": "Seattle", "Date": "08/14/2012", "UnitsSold": 109 },
{ "ProductCategory": "Clothing", "UnitPrice": 34.719, "SellerName": "Mark Slater", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "08/17/2012", "UnitsSold": 478 },
{ "ProductCategory": "Components", "UnitPrice": 23.335, "SellerName": "Claudia Kobayashi", "Country": "Germany", "City": "Heidelberg", "Date": "08/21/2012", "UnitsSold": 184 },
{ "ProductCategory": "Bikes", "UnitPrice": 79.522, "SellerName": "Brandon Mckim", "Country": "Germany", "City": "Hamburg", "Date": "08/21/2012", "UnitsSold": 132 },
{ "ProductCategory": "Components", "UnitPrice": 30.645, "SellerName": "Nicholas Carmona", "Country": "Uruguay", "City": "Montevideo", "Date": "08/22/2012", "UnitsSold": 142 },
{ "ProductCategory": "Bikes", "UnitPrice": 89.887, "SellerName": "Carl Costello", "Country": "Bulgaria", "City": "Sofia", "Date": "08/27/2012", "UnitsSold": 46 },
{ "ProductCategory": "Bikes", "UnitPrice": 83.189, "SellerName": "Walter Pang", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "09/03/2012", "UnitsSold": 102 },
{ "ProductCategory": "Accessories", "UnitPrice": 0.103, "SellerName": "Russell Shorter", "Country": "Japan", "City": "Yokohama", "Date": "09/09/2012", "UnitsSold": 21 },
{ "ProductCategory": "Clothing", "UnitPrice": 36.629, "SellerName": "Monica Freitag", "Country": "UK", "City": "Oxford", "Date": "09/10/2012", "UnitsSold": 442 },
{ "ProductCategory": "Clothing", "UnitPrice": 92.308, "SellerName": "Harry Tyler", "Country": "Uruguay", "City": "Montevideo", "Date": "09/13/2012", "UnitsSold": 254 },
{ "ProductCategory": "Accessories", "UnitPrice": 28.009, "SellerName": "Nicholas Carmona", "Country": "UK", "City": "Birmingham", "Date": "09/13/2012", "UnitsSold": 251 },
{ "ProductCategory": "Components", "UnitPrice": 60.301, "SellerName": "Antonio Charbonneau", "Country": "Bulgaria", "City": "Plovdiv", "Date": "09/15/2012", "UnitsSold": 119 },
{ "ProductCategory": "Bikes", "UnitPrice": 33.007, "SellerName": "Claudia Kobayashi", "Country": "Uruguay", "City": "Ciudad de la Costa", "Date": "09/19/2012", "UnitsSold": 256 },
{ "ProductCategory": "Components", "UnitPrice": 99.002, "SellerName": "John Smith", "Country": "Japan", "City": "Osaka", "Date": "09/23/2012", "UnitsSold": 456 },
{ "ProductCategory": "Components", "UnitPrice": 16.174, "SellerName": "Kathe Pettel", "Country": "US", "City": "Mellvile", "Date": "10/01/2012", "UnitsSold": 430 },
{ "ProductCategory": "Components", "UnitPrice": 72.899, "SellerName": "David Haley", "Country": "Japan", "City": "Yokohama", "Date": "10/02/2012", "UnitsSold": 248 },
{ "ProductCategory": "Components", "UnitPrice": 21.662, "SellerName": "Harold Garvin", "Country": "UK", "City": "Cambrige", "Date": "10/18/2012", "UnitsSold": 440 },
{ "ProductCategory": "Accessories", "UnitPrice": 28.342, "SellerName": "Howard Sprouse", "Country": "Japan", "City": "Osaka", "Date": "10/19/2012", "UnitsSold": 234 },
{ "ProductCategory": "Accessories", "UnitPrice": 80.468, "SellerName": "Benjamin Meekins", "Country": "Japan", "City": "Yokohama", "Date": "10/25/2012", "UnitsSold": 36 },
{ "ProductCategory": "Accessories", "UnitPrice": 97.686, "SellerName": "Harry Tyler", "Country": "US", "City": "Chicago", "Date": "10/26/2012", "UnitsSold": 46 },
{ "ProductCategory": "Components", "UnitPrice": 88.700, "SellerName": "Elisa Longbottom", "Country": "Bulgaria", "City": "Plovdiv", "Date": "11/02/2012", "UnitsSold": 211 },
{ "ProductCategory": "Clothing", "UnitPrice": 67.261, "SellerName": "Walter Pang", "Country": "Japan", "City": "Yokohama", "Date": "11/17/2012", "UnitsSold": 408 },
{ "ProductCategory": "Components", "UnitPrice": 7.145, "SellerName": "Walter Pang", "Country": "Bulgaria", "City": "Sofia", "Date": "11/20/2012", "UnitsSold": 376 }];