language: node_js
node_js:
- '4'
script:
# clone gh-pages
- git clone -b master https://${GH_TOKEN}@${TARGET_REPO} dist

# wipe content in target folder
- rm -rf dist/${TRAVIS_BRANCH}

# build
- gulp build-samples --version ${TRAVIS_BRANCH} --ignite-ui ${IGNITE_ROOT}

# move to dist, set git credentials
- cd dist
- git config user.email "igniteui@infragistics.com"
- git config user.name "igniteui-deploy"

# commit
- git add --all
- if [ -n "$(git status --porcelain)" ]; then git commit -m "Samples for ${TRAVIS_BRANCH} ${TRAVIS_TAG}"; fi
- git push -fq origin master --tags

# whitelist match only xx.x version branches
branches:
  only:
    - /^\d+\.\d$/
env:
  global:
    # GH_TOKEN=
    secure: qJMT7iAwj97jYcVsZuhH4LdpnbP4uCLazw7nyHvJ80NA26qhCuBPuEZS9XJ3J9CyOJ3MStHkwu10G1QZ5HmliFEBh20ZM5gaR1B5JXAoIYnOGKxrgdTDqqgEOp7T7kECH9WILGHOj0BPEafOA/jp8zIUGE86quwvaTvWzd543/zrd31Fcq5TBLuBoYjPFMmCXTyNrkXzpyy3mX9qOgSc6R4Epz1V7oTjiL7JD7hHXtgGR1c6y2UHCc3nKG7AhnQ+7VufchtdJRux/EZXbNfKP3Q1s03fKbIvQ6+Ix00XUKRHwC3kaTCDrmDljiGFrtC+5u+f3PreSdtxJmDnvHBeB8rB8RgltVdNULjyKj5yEeHBRq9soxXDu1TrYf8GJYOKI0Tp2CWwJYhmDeOLmkau9DWkVHFQNa9r3gAsqdxrmDdLQhAMIcJ5CMHRjdu+Covihvlk3tRxNfFhrKH3d6K+3ZvJBCWBHe5o88+4VHlT+WmExVOKJD8CXweXDF5JS4PeuT2PfyXCfulfDRTZOEz3k3cKnp0iIdwGEfu8QCftXoof5YRFABtr26wZA9NKrT/CxRaoTQV3urfND+IPRJ/38FpCAGD2n6LKfSsoZ8y99zpsfbLX1Po4xT3E3TuRpgBvlJN76VOimdO7odQfigYJPPfj5B+5EDtDs4Nb8833TVY=
