language: node_js
node_js:
- '4'
script:
# clone gh-pages
- git clone -b master https://${GH_TOKEN}@${TARGET_REPO} dist

# wipe content in target folder
- rm -rf dist/${TRAVIS_BRANCH}

# build
- gulp build-samples --version ${TRAVIS_BRANCH} --ignite-ui ${IGNITE_ROOT}

# move to dist, set git credentials
- cd dist
- git config user.email "igniteui@infragistics.com"
- git config user.name "igniteui-deploy"

# commit
- git add --all
- if [ -n "$(git status --porcelain)" ]; then git commit -m "Samples for ${TRAVIS_BRANCH} ${TRAVIS_TAG}"; fi
- git push -fq origin master --tags

# whitelist match only xx.x version branches
branches:
  only:
    - /^\d+\.\d$/
env:
  global:
    # GH_TOKEN=
    secure: Vb+vvUbXkiNe9V3QdHGCXKf28ijIyDfq014x1qfJC8TihhBVPb1X+GrhzIYkRZuc3+gMW0unqaFoUhQRWe20mK29SBYu+JnXZFcSxKGIdf0Rvvwj6zqimF28itOUmGbfDNstx6KAPUHmHtvwCo3ShU25sJQ+SwWF1Wu3Rns7YLBRzlA0fgFywuCKHJTEULUmUVIKb8j+ji0hRKtrJ/HiJ6W3pPPnYPNE1z38CAMnym5Sehf9Nk4veJUz/NY/hDtJFmxtqPEbxCLRhvjCxPKUJXs6zdmiE30AzjVd824XazcMAdcilmaYOqWdJqqh1YeTJwkAkgu0TX6JaDnkY3joa7z8l4uIVFPnbu4l+IOMAuJXf0KWKYtY3sya8pSlUdZYI32OoaDwPW3mRmva3bWiQxvLOiA0UqRlD2O0sEhBgOGWipWrm3Jtq4+lYrDBEW8uM9vb6kl7MSapj4RBQVnDKOnDYkYGbgPlFjDIrq2T4GV7fldM0tEJzXyxgB6YIU/RbYiYFqmAT75vRirVOsIe8GSyVQYW4ynKXn2JJI1aK8v5/78iGfAacKSTmkLal+DEy0wo9b7yFb9zmkLEl8YS2wWbT7xtncC1qkQw7PmzcQV2erlVUa71t/no4D4YKEeWZZXH2zox9q5rWaUMJamrwdORQpgzYA7v933DojV1Uiw=
